const feb_2023_crimes_geojson = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4870505, 34.02846918],
      },
      properties: {
        'Event #': 2023005906,
        DATE: '2/1/23',
        EVENT: 'MISCELLANEOUS INCIDENT REPORT',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '1200-BLOCK 16TH ST.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0239',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4431252, 34.0592649],
      },
      properties: {
        'Event #': 2023005920,
        DATE: '2/1/23',
        EVENT: 'GRAND THEFT - OTHER\n (2) MAKE FICT CHECK INT DFRD',
        CATEGORY: 'THEFT/BURGLARY\n OTHER/MULTIPLE',
        LOCATION: 'HAMMER MUSEUM\n 10889 WILSHIRE BLVD.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0240',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4539115, 34.070354],
      },
      properties: {
        'Event #': 2023005947,
        DATE: '2/1/23',
        EVENT: 'INFLICT CORPORAL INJURY/ SIMPLE',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '400-BLOCK KELTON AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0242',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.448127, 34.06850154],
      },
      properties: {
        'Event #': 2023005954,
        DATE: '2/1/23',
        EVENT: 'TRAFFIC COLLISION REPORT',
        CATEGORY: 'TRAFFIC/VEHICULAR',
        LOCATION: 'EH AND S SERVICES BUILDING\n 550 CHARLES E YOUNG DRIVE W',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '23-0241',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4461902, 34.0709696],
      },
      properties: {
        'Event #': 2023005966,
        DATE: '2/1/23',
        EVENT: 'GRAND THEFT - AUTO',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '100 BRUINWALK',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0243',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4409969, 34.075885],
      },
      properties: {
        'Event #': 2023005991,
        DATE: '2/1/23',
        EVENT: 'GRAND THEFT - BICYCLES',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'BROAD ART CENTER\n 240 CHARLES E YOUNG DRIVE N',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '23-0244',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4440863, 34.0715644],
      },
      properties: {
        'Event #': 2023006007,
        DATE: '2/1/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'STUDENT ACTIVITIES CENTER\n 220 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '23-0245',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4291114, 34.0289804],
      },
      properties: {
        'Event #': 2023006035,
        DATE: '2/1/23',
        EVENT: 'POSSESS CONTROLLED SUBSTANCE',
        CATEGORY: 'DRUG/CONTROLLED SUBSTANCE',
        LOCATION: '2850 S SEPULVEDA BLVD.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0248',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4527487, 34.0739077],
      },
      properties: {
        'Event #': 2023006080,
        DATE: '2/2/23',
        EVENT:
          'GIVE FALSE IDENTIFICATION TO PO\n (2) UNAUTHORIZED ENTRY OF DWELLING',
        CATEGORY: 'OTHER/MULTIPLE\n TRESPASSING',
        LOCATION: 'HEDRICK SUMMIT\n 240 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0250',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4431563, 34.07528089],
      },
      properties: {
        'Event #': 2023006239,
        DATE: '2/2/23',
        EVENT:
          'PARAPHERNALIA - POSSESS UNLAWFUL\n (2) CA REGS - UNAUTHORIZED CAMPING ON UNIVERSITY PROPERTY',
        CATEGORY: 'DRUG/CONTROLLED SUBSTANCE\n TRESPASSING',
        LOCATION: 'PARKING STRUCTURE 5\n 302 SYCAMORE CT',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0254',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4484099, 34.0703932],
      },
      properties: {
        'Event #': 2023006248,
        DATE: '2/2/23',
        EVENT: 'TRAFFIC COLLISION REPORT',
        CATEGORY: 'TRAFFIC/VEHICULAR',
        LOCATION: 'LOS ANGELES TENNIS CENTER\n 420 CHARLES E YOUNG DRIVE W',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '23-0255',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4484361, 34.0666011],
      },
      properties: {
        'Event #': 2023006256,
        DATE: '2/2/23',
        EVENT: 'TRESPASS - REFUSE TO LEAVE PROPERTY',
        CATEGORY: 'TRESPASSING',
        LOCATION: '638 LANDFAIR APARTMENTS\n 638 LANDFAIR AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0256',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4475093, 34.0610758],
      },
      properties: {
        'Event #': 2023006273,
        DATE: '2/2/23',
        EVENT: 'PETTY THEFT - OTHER',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'UCLA BLOOD AND PLATELET CENTER\n 1045 GAYLEY AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0258',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4401283, 34.0742539],
      },
      properties: {
        'Event #': 2023006321,
        DATE: '2/2/23',
        EVENT: 'WEAR/ETC ID/ETC - IMPERS PO',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'BUNCHE HALL\n 315 PORTOLA PLAZA',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '23-0260',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4485786, 34.0633872],
      },
      properties: {
        'Event #': 2023006351,
        DATE: '2/2/23',
        EVENT: 'BURGLARY\n (2) POSSESS CONTROLLED SUBSTANCE',
        CATEGORY: 'THEFT/BURGLARY\n DRUG/CONTROLLED SUBSTANCE',
        LOCATION: '10984 LE CONTE AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0261',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4454214, 34.0636831],
      },
      properties: {
        'Event #': 2023006487,
        DATE: '2/3/23',
        EVENT: 'TRAFFIC COLLISION REPORT',
        CATEGORY: 'TRAFFIC/VEHICULAR',
        LOCATION: '899 WESTWOOD PLAZA/LE CONTE AVE.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '23-0265',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4253126, 34.1500782],
      },
      properties: {
        'Event #': 2023006511,
        DATE: '2/3/23',
        EVENT: 'IDENTITY THEFT - GET CREDIT/ETC OTHER`S ID',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '13406 MOORPARK ST.',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '23-0268',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4484361, 34.0666011],
      },
      properties: {
        'Event #': 2023006518,
        DATE: '2/3/23',
        EVENT: 'VANDALISM - DAMAGE PROPERTY',
        CATEGORY: 'VANDALISM',
        LOCATION: '638 LANDFAIR APARTMENTS\n 638 LANDFAIR AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0269',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4432392, 34.0692388],
      },
      properties: {
        'Event #': 2023006536,
        DATE: '2/3/23',
        EVENT: 'GRAND THEFT - BICYCLES',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'BOELTER HALL\n 580 PORTOLA PLAZA',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0270',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4458242, 34.0655792],
      },
      properties: {
        'Event #': 2023006538,
        DATE: '2/3/23',
        EVENT: 'FIRE ALARM',
        CATEGORY: 'ARSON',
        LOCATION:
          'MEDICAL PLAZA 100 MANOUKIAN MEDICAL BLDG REPORT TAKEN\n 100 MEDICAL PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '-',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4526108, 34.0641774],
      },
      properties: {
        'Event #': 2023006582,
        DATE: '2/4/23',
        EVENT:
          'DUI ALCOHOL\n (2) DUI ALCOHOL/0.08 PERCENT\n (3) TRAFFIC COLLISION REPORT',
        CATEGORY: 'TRAFFIC/VEHICULAR\n TRAFFIC/VEHICULAR\n TRAFFIC/VEHICULAR',
        LOCATION: '11088 STRATHMORE DRIVE/KELTON AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0273',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4458242, 34.0655792],
      },
      properties: {
        'Event #': 2023006583,
        DATE: '2/4/23',
        EVENT:
          'PETTY THEFT - OTHER\n (2) FAIL TO REGISTER/ETC - FELONY SEX OFFENDER W/PRIOR\n (3) CA REGS - VIOLATE CURFEW',
        CATEGORY: 'THEFT/BURGLARY\n RAPE/OTHER SEX CRIME\n OTHER/MULTIPLE',
        LOCATION:
          'MEDICAL PLAZA 100 MANOUKIAN MEDICAL BLDG REPORT TAKEN\n 100 MEDICAL PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0274',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4496915, 34.067988],
      },
      properties: {
        'Event #': 2023006630,
        DATE: '2/4/23',
        EVENT: 'OBTAIN MONEY/ETC BY FALSE PRETENSES (OVER $950)',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '10919 STRATHMORE DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0276',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.450173, 34.0708126],
      },
      properties: {
        'Event #': 2023006636,
        DATE: '2/4/23',
        EVENT: 'VANDALISM - DEFACE PROPERTY',
        CATEGORY: 'VANDALISM',
        LOCATION: 'DE NEVE PLAZA\n 351 CHARLES E YOUNG DRIVE W',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '23-0275',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4449481, 34.0627506],
      },
      properties: {
        'Event #': 2023006710,
        DATE: '2/4/23',
        EVENT: 'VANDALISM - DEFACE PROPERTY',
        CATEGORY: 'VANDALISM',
        LOCATION: 'BLUESTONE LANE COFFEE SHOP\n 950 WESTWOOD BLVD.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0277',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4450955, 34.0634782],
      },
      properties: {
        'Event #': 2023006711,
        DATE: '2/4/23',
        EVENT:
          'GIVE FALSE IDENTIFICATION TO PO\n (2) VANDALISM - DEFACE PROPERTY\n (3) WARRANT ARREST',
        CATEGORY: 'OTHER/MULTIPLE\n VANDALISM\n OTHER/MULTIPLE',
        LOCATION: '800 WESTWOOD BLVD./LE CONTE AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0278',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4498079, 34.0686537],
      },
      properties: {
        'Event #': 2023006796,
        DATE: '2/5/23',
        EVENT:
          'POSSESS CONTROLLED SUBSTANCE\n (2) PARAPHERNALIA - POSSESS UNLAWFUL\n (3) FELON PURCHASE/POSSESS/USE TEAR GAS/ETC\n (4) DISORDERLY CONDUCT - LODGE WITHOUT OWNERS CONSENT',
        CATEGORY:
          'DRUG/CONTROLLED SUBSTANCE\n DRUG/CONTROLLED SUBSTANCE\n OTHER/MULTIPLE\n TRESPASSING',
        LOCATION: 'GAYLEY TOWERS APARTMENTS\n 565 GAYLEY AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0282',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4527763, 34.073334],
      },
      properties: {
        'Event #': 2023006802,
        DATE: '2/5/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '310 RIEBER HALL TURNAROUND',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0281',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4469018, 34.0731093],
      },
      properties: {
        'Event #': 2023006814,
        DATE: '2/5/23',
        EVENT: 'KIDNAPPING',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'PARKING STRUCTURE 7\n 336 CHARLES E YOUNG DRIVE N',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0283',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4479294, 34.0651113],
      },
      properties: {
        'Event #': 2023006816,
        DATE: '2/5/23',
        EVENT: 'KIDNAPPING\n (2) ROBBERY',
        CATEGORY: 'OTHER/MULTIPLE\n OTHER/MULTIPLE',
        LOCATION: 'PARKING STRUCTURE 1\n 720 GAYLEY AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0284',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4496448, 34.0719775],
      },
      properties: {
        'Event #': 2023006850,
        DATE: '2/6/23',
        EVENT: 'PETTY THEFT - BICYCLES',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'SPROUL HALL TURNAROUND\n 350 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0285',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4869941, 34.0286559],
      },
      properties: {
        'Event #': 2023006853,
        DATE: '2/6/23',
        EVENT: 'VANDALISM - DEFACE PROPERTY',
        CATEGORY: 'VANDALISM',
        LOCATION: 'MEDICAL BUILDING\n 1601 WILSHIRE BOULEVARD',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '23-0286',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4865131, 34.0265628],
      },
      properties: {
        'Event #': 2023006890,
        DATE: '2/6/23',
        EVENT:
          'BATTERY ON PEACE OFFICER/EMERGENCY PERSONNEL/ETC\n (2) TRESPASS - REFUSE TO LEAVE PROPERTY',
        CATEGORY: 'ASSAULT/BATTERY\n TRESPASSING',
        LOCATION: '1255 15TH ST.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0287',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-77.5549696, 34.4954448],
      },
      properties: {
        'Event #': 2023006911,
        DATE: '2/6/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'HOLLY RIDGE\n 345 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '23-0289',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4449257, 34.0695297],
      },
      properties: {
        'Event #': 2023006926,
        DATE: '2/6/23',
        EVENT: 'SEND/ETC FALSE FIRE ALARM BY ANY METHOD\n (2) WARRANT ARREST',
        CATEGORY: 'ARSON\n OTHER/MULTIPLE',
        LOCATION: 'KERCKHOFF HALL\n 310 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0292',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4447967, 34.0726384],
      },
      properties: {
        'Event #': 2023006931,
        DATE: '2/6/23',
        EVENT:
          'BATTERY ON PEACE OFFICER/EMERGENCY PERSONNEL/ETC\n (2) WARRANT ARREST',
        CATEGORY: 'ASSAULT/BATTERY\n OTHER/MULTIPLE',
        LOCATION: 'PARKING STRUCTURE 4\n 219 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0293',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4476299, 34.0704747],
      },
      properties: {
        'Event #': 2023006938,
        DATE: '2/6/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'ACOSTA TRAINING CENTER\n 410 CHARLES E YOUNG DRIVE W',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0295',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4505162, 34.0628349],
      },
      properties: {
        'Event #': 2023006964,
        DATE: '2/6/23',
        EVENT: 'OBTAIN MONEY/ETC BY FALSE PRETENSES',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'PALO VERDE\n 910 WEYBURN PLACE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0294',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4420203, 34.0722226],
      },
      properties: {
        'Event #': 2023006968,
        DATE: '2/6/23',
        EVENT: 'TAMPER WITH VEHICLE',
        CATEGORY: 'VANDALISM',
        LOCATION: '10745 DICKSON PLAZA',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0298',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4460531, 34.0646208],
      },
      properties: {
        'Event #': 2023006976,
        DATE: '2/6/23',
        EVENT:
          'ASSAULT DEADLY WEAPON - NOT FIREARM\n (2) SMUGGLE CNTL SUB JL/PRSN\n (3) PARAPHERNALIA - POSSESS UNLAWFUL\n (4) CARRY CONCEALED DIRK OR DAGGER\n (5) WARRANT ARREST',
        CATEGORY:
          'ARSON\n OTHER/MULTIPLE\n DRUG/CONTROLLED SUBSTANCE\n OTHER/MULTIPLE\n OTHER/MULTIPLE',
        LOCATION: '300 MEDICAL PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0296',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4491309, 34.0613656],
      },
      properties: {
        'Event #': 2023006978,
        DATE: '2/6/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'PASEO WEYBURN TERRACE\n 11000 WEYBURN DRIVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0297',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4530909, 34.0715897],
      },
      properties: {
        'Event #': 2023007000,
        DATE: '2/7/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'SAXON SUITES\n 325 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0299',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4512429, 34.0682774],
      },
      properties: {
        'Event #': 2023007049,
        DATE: '2/7/23',
        EVENT: 'GRAND THEFT - MOTOR VEH PARTS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '10940 OPHIR DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0300',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4515229, 34.0716817],
      },
      properties: {
        'Event #': 2023007050,
        DATE: '2/7/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'RIEBER HALL\n 310 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '23-0301',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-77.5549696, 34.4954448],
      },
      properties: {
        'Event #': 2023007061,
        DATE: '2/7/23',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'HOLLY RIDGE\n 345 DE NEVE DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0303',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4530909, 34.0667935],
      },
      properties: {
        'Event #': 2023007073,
        DATE: '2/7/23',
        EVENT: 'GRAND THEFT - MOTOR VEH PARTS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '606 LEVERING AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0304',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4491115, 34.0696351],
      },
      properties: {
        'Event #': 2023007127,
        DATE: '2/7/23',
        EVENT: 'TRAFFIC COLLISION REPORT\n TRAFFIC COLLISION REPORT',
        CATEGORY: 'TRAFFIC/VEHICULAR\n TRAFFIC/VEHICULAR',
        LOCATION: 'BRADLEY INTERNATIONAL HALL\n 417 CHARLES E YOUNG DRIVE W',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '23-0306',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4287779, 34.0237236],
      },
      properties: {
        'Event #': 2023007142,
        DATE: '2/8/23',
        EVENT: 'INFLICT CORPORAL INJURY /AGGRAVATED',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '3200-BLOCK SAWTELLE BLVD.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0307',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4252858, 34.0226508],
      },
      properties: {
        'Event #': 2023007163,
        DATE: '2/8/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '3251 S SEPULVEDA BLVD.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0311',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4477465, 34.0599645],
      },
      properties: {
        'Event #': 2023007179,
        DATE: '2/8/23',
        EVENT: 'GRAND THEFT - MOTOR VEH PARTS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '1070 VETERAN AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0310',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.440385, 34.0673808],
      },
      properties: {
        'Event #': 2023007228,
        DATE: '2/8/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION:
          'TERASAKI LIFE SCIENCES BUILDING\n 610 CHARLES E YOUNG DRIVE S',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '23-0315',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4870505, 34.02846918],
      },
      properties: {
        'Event #': 2023007361,
        DATE: '2/9/23',
        EVENT: 'BATTERY - SPOUSE/EX SPOUSE/DATE/ETC',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: '1200-BLOCK 16TH ST.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0318',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4449232, 34.0628113],
      },
      properties: {
        'Event #': 2023007368,
        DATE: '2/9/23',
        EVENT: 'OBTAIN MONEY/ETC BY FALSE PRETENSES (OVER $950)',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '924 WESTWOOD BLVD.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0319',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4449102, 34.0658188],
      },
      properties: {
        'Event #': 2023007373,
        DATE: '2/9/23',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'SEMEL INSTITUTE\n 760 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0320',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4501921, 34.07061877],
      },
      properties: {
        'Event #': 2023007380,
        DATE: '2/9/23',
        EVENT: 'THREATEN CRIME W/INTENT TO TERRORIZE\n (2) EXTORTION',
        CATEGORY: 'OTHER/MULTIPLE\n OTHER/MULTIPLE',
        LOCATION: 'BIRCH HEIGHTS\n 351 CHARLES E YOUNG DRIVE W',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0321',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4480285, 34.0625267],
      },
      properties: {
        'Event #': 2023007544,
        DATE: '2/10/23',
        EVENT: 'RECKLESS DRIVING - HIGHWAY',
        CATEGORY: 'TRAFFIC/VEHICULAR',
        LOCATION: 'FAT SALS DELI\n 972 GAYLEY AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0323',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4445984, 34.0596499],
      },
      properties: {
        'Event #': 2023007554,
        DATE: '2/10/23',
        EVENT:
          'FELON/ADDICT/POSSESS/ETC FIREARM\n (2) FUGITIVE FROM JUSTICE - WARRANT ARREST\n (3) WARRANT ARREST',
        CATEGORY: 'ARSON\n OTHER/MULTIPLE\n OTHER/MULTIPLE',
        LOCATION: '1159 WESTWOOD BLVD./LINDBROOK DRIVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0325',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4449102, 34.0658188],
      },
      properties: {
        'Event #': 2023007557,
        DATE: '2/10/23',
        EVENT: 'WARRANT ARREST',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'SEMEL INSTITUTE\n 760 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0326',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4233256, 34.0212179],
      },
      properties: {
        'Event #': 2023007586,
        DATE: '2/10/23',
        EVENT: 'IDENTITY THEFT - GET CREDIT/ETC OTHER`S ID',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '11140 ROSE AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0327',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4231918, 34.0211361],
      },
      properties: {
        'Event #': 2023007601,
        DATE: '2/10/23',
        EVENT: 'BURGLARY - HOT PROWL',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'ROSE APARTMENTS\n 11140 ROSE AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0328',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4400147, 34.0711317],
      },
      properties: {
        'Event #': 2023007613,
        DATE: '2/10/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'SCHOENBERG MUSIC BUILDING\n 445 CHARLES E YOUNG DRIVE E',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0329',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4401988, 34.0692348],
      },
      properties: {
        'Event #': 2023007617,
        DATE: '2/10/23',
        EVENT: 'TAMPER WITH VEHICLE',
        CATEGORY: 'VANDALISM',
        LOCATION: 'PARKING STRUCTURE 2\n 602 CHARLES E YOUNG DRIVE E',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '23-0331',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.44554, 34.0495731],
      },
      properties: {
        'Event #': 2023007683,
        DATE: '2/11/23',
        EVENT:
          'POSSESS CONTROLLED SUBSTANCE\n (2) PARAPHERNALIA - POSSESS UNLAWFUL\n (3) WARRANT ARREST',
        CATEGORY:
          'DRUG/CONTROLLED SUBSTANCE\n DRUG/CONTROLLED SUBSTANCE\n OTHER/MULTIPLE',
        LOCATION: '1552 S SEPULVEDA BLVD./MASSACHUSETTS AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0334',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4452885, 34.0702103],
      },
      properties: {
        'Event #': 2023007719,
        DATE: '2/11/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'MORGAN ATHLETIC CENTER\n 325 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0335',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4466512, 34.0652918],
      },
      properties: {
        'Event #': 2023007722,
        DATE: '2/11/23',
        EVENT:
          'BATTERY ON PEACE OFFICER/EMERGENCY PERSONNEL/ETC\n (2) WARRANT ARREST',
        CATEGORY: 'ASSAULT/BATTERY\n OTHER/MULTIPLE',
        LOCATION: 'RONALD REAGAN UCLA MEDICAL CENTER\n 757 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0337',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4485786, 34.0633872],
      },
      properties: {
        'Event #': 2023007723,
        DATE: '2/11/23',
        EVENT: 'VANDALISM - DAMAGE PROPERTY',
        CATEGORY: 'VANDALISM',
        LOCATION: 'CHEVRON GAS STATION\n 10984 LE CONTE AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0336',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4472819, 34.0631064],
      },
      properties: {
        'Event #': 2023007749,
        DATE: '2/11/23',
        EVENT: 'BATTERY',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: '925 BROXTON AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0344',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4498788, 34.0717948],
      },
      properties: {
        'Event #': 2023007822,
        DATE: '2/11/23',
        EVENT: 'PETTY THEFT - OTHER',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'BRUIN PLATE\n 350 CHARLES E YOUNG DRIVE WEST',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0339',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4491309, 34.0613656],
      },
      properties: {
        'Event #': 2023007823,
        DATE: '2/11/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '11000 WEYBURN DRIVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0340',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4267328, 34.0207593],
      },
      properties: {
        'Event #': 2023007964,
        DATE: '2/12/23',
        EVENT: 'TAMPER WITH VEHICLE',
        CATEGORY: 'VANDALISM',
        LOCATION: 'SAWTELLE PARKING STRUCTURE\n 3340 SAWTELLE BLVD.',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0342',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4507392, 34.0711897],
      },
      properties: {
        'Event #': 2023007967,
        DATE: '2/12/23',
        EVENT: 'GRAND THEFT - MOTOR VEH PARTS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'PARKING STRUCTURE SV\n 332 DE NEVE DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0341',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4480529, 34.05905926],
      },
      properties: {
        'Event #': 2023007980,
        DATE: '2/12/23',
        EVENT: 'GRAND THEFT - BICYCLES',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '11100 KINROSS AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0343',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4401283, 34.0742539],
      },
      properties: {
        'Event #': 2023007992,
        DATE: '2/12/23',
        EVENT: 'TRESPASSING\n (2) WARRANT ARREST',
        CATEGORY: 'TRESPASSING\n OTHER/MULTIPLE',
        LOCATION: 'BUNCHE HALL\n 315 PORTOLA PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0347',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4452612, 34.0649793],
      },
      properties: {
        'Event #': 2023007996,
        DATE: '2/12/23',
        EVENT: 'RAPE; VICT INCPBL OF CNSNT',
        CATEGORY: 'RAPE/OTHER SEX CRIME',
        LOCATION: '800-BLOCK WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0348',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.3199033, 33.7197873],
      },
      properties: {
        'Event #': 2023008027,
        DATE: '2/13/23',
        EVENT: 'IDENTITY THEFT - GET CREDIT/ETC OTHER`S ID',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '3512 GRAYSBY AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0349',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4423562, 34.0642829],
      },
      properties: {
        'Event #': 2023008046,
        DATE: '2/13/23',
        EVENT: 'BURGLARY REPORT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'CENTER FOR HEALTH SCIENCES\n 10833 LE CONTE AVE.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '23-0350',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4529734, 34.0644822],
      },
      properties: {
        'Event #': 2023008054,
        DATE: '2/13/23',
        EVENT: 'GRAND THEFT - MOTOR VEH PARTS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '683 KELTON AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0352',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4453406, 34.0715641],
      },
      properties: {
        'Event #': 2023008055,
        DATE: '2/13/23',
        EVENT: 'GRAND THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'WOODEN CENTER\n 221 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0351',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4489053, 34.0615046],
      },
      properties: {
        'Event #': 2023008147,
        DATE: '2/13/23',
        EVENT:
          'OBSTRUCT/RESIST EXEC OFCR\n (2) GIVE FALSE IDENTIFICATION TO PO\n (3) VANDALISM - DAMAGE PROPERTY\n (4) WARRANT ARREST',
        CATEGORY:
          'OTHER/MULTIPLE\n OTHER/MULTIPLE\n VANDALISM\n OTHER/MULTIPLE',
        LOCATION: 'WEYBURN COMMONS\n 11020 WEYBURN DRIVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0355',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4463584, 34.0650983],
      },
      properties: {
        'Event #': 2023008158,
        DATE: '2/14/23',
        EVENT:
          'POSSESS CONTROLLED SUBSTANCES WITHOUT A PRESCRIPTION\n (2) PARAPHERNALIA - POSSESS UNLAWFUL',
        CATEGORY: 'DRUG/CONTROLLED SUBSTANCE\n DRUG/CONTROLLED SUBSTANCE',
        LOCATION: 'MEDICAL PLAZA 200 PETER MORTON BUILDING\n 200 MEDICAL PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0356',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4866355, 34.0274739],
      },
      properties: {
        'Event #': 2023008159,
        DATE: '2/14/23',
        EVENT: 'BATTERY',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: 'UCLA SANTA MONICA HOSPITAL\n 1250 16TH ST.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0357',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4486342, 34.0638872],
      },
      properties: {
        'Event #': 2023008173,
        DATE: '2/14/23',
        EVENT:
          'GIVE FALSE IDENTIFICATION TO PO\n (2) POSSESS CONTROLLED SUBSTANCE',
        CATEGORY: 'OTHER/MULTIPLE\n DRUG/CONTROLLED SUBSTANCE',
        LOCATION: 'GAYLEY HEIGHTS APARTMENTS\n 10995 LE CONTE AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0358',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4471374, 34.0607042],
      },
      properties: {
        'Event #': 2023008207,
        DATE: '2/14/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'GAYLEY UNEX\n 1083 GAYLEY AVE.',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0360',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4426416, 34.0704197],
      },
      properties: {
        'Event #': 2023008244,
        DATE: '2/14/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'MOORE HALL\n 457 PORTOLA PLAZA',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0361',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4466512, 34.0652918],
      },
      properties: {
        'Event #': 2023008345,
        DATE: '2/15/23',
        EVENT: 'BATTERY AGAINST EMERGENCY PERSONS/ETC',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: 'RRMC ER\n 757 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0362',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4462571, 34.0501914],
      },
      properties: {
        'Event #': 2023008366,
        DATE: '2/15/23',
        EVENT: 'IDENTITY THEFT - GET CREDIT/ETC OTHER`S ID',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION:
          'UNIVERSITY CREDIT UNION MAIN BRANCH UCU\n 1500 S SEPULVEDA BLVD.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0364',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4490299, 34.0621787],
      },
      properties: {
        'Event #': 2023008369,
        DATE: '2/15/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'WEYBURN TERRACE APARTMENTS\n 925 WEYBURN PLACE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0363',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4423562, 34.0642829],
      },
      properties: {
        'Event #': 2023008390,
        DATE: '2/15/23',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'CENTER FOR HEALTH SCIENCES\n 10833 LE CONTE AVE.',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0366',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4510504, 34.0729717],
      },
      properties: {
        'Event #': 2023008417,
        DATE: '2/15/23',
        EVENT: 'OBTAIN MONEY/ETC BY FALSE PRETENSES',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'DELTA TERRACE\n 330 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0367',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4393181, 34.0728027],
      },
      properties: {
        'Event #': 2023008481,
        DATE: '2/15/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'DODD HALL\n 390 PORTOLA PLAZA',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '23-0368',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4499425, 34.0625088],
      },
      properties: {
        'Event #': 2023008501,
        DATE: '2/15/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '900 WEYBURN PLACE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0369',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4486879, 34.0589677],
      },
      properties: {
        'Event #': 2023008523,
        DATE: '2/16/23',
        EVENT: 'OBSTRUCT/RESIST/ETC PUBLIC/P OFFICER/EMT',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '1099 VETERAN AVE./KINROSS AVE.',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0370',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4499786, 34.0729953],
      },
      properties: {
        'Event #': 2023008528,
        DATE: '2/16/23',
        EVENT: 'EXTORTN COLOR OFFCL RIGHT',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'CANYON POINT\n 330 DE NEVE DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0371',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4454037, 34.0673085],
      },
      properties: {
        'Event #': 2023008532,
        DATE: '2/16/23',
        EVENT: 'THREATEN CRIME W/INTENT TO TERRORIZE',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'UCLA POLICE STATION\n 601 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0372',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4460531, 34.0644164],
      },
      properties: {
        'Event #': 2023008594,
        DATE: '2/16/23',
        EVENT: 'GRAND THEFT - BICYCLES',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'MEDICAL PLAZA 300 GOLDBERG MEDICAL BLDG\n 300 MEDICAL PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0374',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4421853, 34.0547848],
      },
      properties: {
        'Event #': 2023008619,
        DATE: '2/16/23',
        EVENT: 'INFLICT CORPORAL INJURY /AGGRAVATED',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '1400-BLOCK MIDVALE AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0377',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4213796, 34.0135098],
      },
      properties: {
        'Event #': 2023008620,
        DATE: '2/16/23',
        EVENT: 'PARAPHERNALIA - POSSESS UNLAWFUL',
        CATEGORY: 'DRUG/CONTROLLED SUBSTANCE',
        LOCATION: '3698 SAWTELLE BLVD./REGENT ST.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0375',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4505162, 34.0628349],
      },
      properties: {
        'Event #': 2023008625,
        DATE: '2/16/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'PALO VERDE\n 910 WEYBURN PLACE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0376',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4550218, 34.0703277],
      },
      properties: {
        'Event #': 2023008639,
        DATE: '2/16/23',
        EVENT: 'MISDEMEANOR HIT AND RUN REPORT',
        CATEGORY: 'TRAFFIC/VEHICULAR',
        LOCATION: 'VETERAN AVE./MONTANA AVE.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '23-0378',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4491309, 34.0613656],
      },
      properties: {
        'Event #': 2023008643,
        DATE: '2/16/23',
        EVENT: 'OBTAIN MONEY/ETC BY FALSE PRETENSES (OVER $950)',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'PASEO WEYBURN TERRACE\n 11000 WEYBURN DRIVE',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '23-0379',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4440547, 34.0630407],
      },
      properties: {
        'Event #': 2023008695,
        DATE: '2/16/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'RALPHS\n 10861 LE CONTE AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0383',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4477101, 34.0668566],
      },
      properties: {
        'Event #': 2023008696,
        DATE: '2/16/23',
        EVENT: 'TRAFFIC COLLISION REPORT',
        CATEGORY: 'TRAFFIC/VEHICULAR',
        LOCATION: '661 GAYLEY AVE./CHARLES E YOUNG DRIVE S',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '23-0384',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4499425, 34.0625088],
      },
      properties: {
        'Event #': 2023008719,
        DATE: '2/16/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'TIPUANA\n 900 WEYBURN PLACE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0386',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4510907, 34.06521047],
      },
      properties: {
        'Event #': 2023008721,
        DATE: '2/16/23',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '11017 STRATHMORE APARTMENTS\n 11017 STRATHMORE DRIVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0385',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4441451, 34.070418],
      },
      properties: {
        'Event #': 2023008752,
        DATE: '2/16/23',
        EVENT: 'PARAPHERNALIA - POSSESS UNLAWFUL',
        CATEGORY: 'DRUG/CONTROLLED SUBSTANCE',
        LOCATION: 'ACKERMAN UNION\n 308 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0389',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4475414, 34.0693608],
      },
      properties: {
        'Event #': 2023008903,
        DATE: '2/17/23',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'WASSERMAN FOOTBALL CENTER\n 430 CHARLES E YOUNG DRIVE W',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0394',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4468214, 34.05948109],
      },
      properties: {
        'Event #': 2023008907,
        DATE: '2/17/23',
        EVENT: 'PETTY THEFT - OTHER',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'KINROSS RECREATION CENTER\n 11000 KINROSS AVE.',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0392',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4048851, 34.0178904],
      },
      properties: {
        'Event #': 2023008908,
        DATE: '2/17/23',
        EVENT: 'PETTY THEFT - MAIL OR PACKAGE',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '3770 KEYSTONE AVE.',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0393',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4068804, 34.02004921],
      },
      properties: {
        'Event #': 2023008909,
        DATE: '2/17/23',
        EVENT: 'INT CRUELTY TO ANIMALS',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '3767 KEYSTONE AVE.',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '23-0395',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4537072, 34.0735276],
      },
      properties: {
        'Event #': 2023009001,
        DATE: '2/17/23',
        EVENT: 'ADW WITH FORCE - POSSIBLE GBI',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'HITCH SUITES\n 245 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0397',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.445055, 34.063247],
      },
      properties: {
        'Event #': 2023009026,
        DATE: '2/17/23',
        EVENT: 'OFFENSIVE WORDS IN PUBLIC PLACE',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'WESTWOOD PLAZA BUILDING\n 924 WESTWOOD BLVD.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0396',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4421766, 34.0716399],
      },
      properties: {
        'Event #': 2023009040,
        DATE: '2/17/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'POWELL LIBRARY\n 10740 DICKSON PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0398',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4481164, 34.0644638],
      },
      properties: {
        'Event #': 2023009108,
        DATE: '2/18/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '10995 GAYLEY AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0399',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4515557, 34.0686418],
      },
      properties: {
        'Event #': 2023009112,
        DATE: '2/18/23',
        EVENT: 'VANDALISM - DAMAGE PROPERTY',
        CATEGORY: 'VANDALISM',
        LOCATION: '10947 OPHIR DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0400',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4480285, 34.0625267],
      },
      properties: {
        'Event #': 2023009185,
        DATE: '2/18/23',
        EVENT:
          'CARRY LOADED FIREARM ON/IN PERSON/VEHICLE - PUBLIC PLACE\n (2) OBSTRUCT/RESIST/ETC PUBLIC/P OFFICER/EMT',
        CATEGORY: 'ARSON\n OTHER/MULTIPLE',
        LOCATION: 'FAT SALS DELI\n 972 GAYLEY AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0401',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4466512, 34.0652918],
      },
      properties: {
        'Event #': 2023009354,
        DATE: '2/19/23',
        EVENT: 'POSSESS/ETC BAD/ETC CHECK/ETC',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'RONALD REAGAN UCLA MEDICAL CENTER\n 757 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0404',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4476299, 34.0704747],
      },
      properties: {
        'Event #': 2023009492,
        DATE: '2/20/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'ACOSTA TRAINING CENTER\n 410 CHARLES E YOUNG DRIVE W',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0410',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4477099, 34.0654002],
      },
      properties: {
        'Event #': 2023009494,
        DATE: '2/20/23',
        EVENT: 'TRAFFIC COLLIS UNIVERSITY VEH',
        CATEGORY: 'TRAFFIC/VEHICULAR',
        LOCATION: '700-BLK GAYLEY AVE.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '23-0409',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4499425, 34.0625088],
      },
      properties: {
        'Event #': 2023009519,
        DATE: '2/20/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'TIPUANA\n 900 WEYBURN PLACE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0412',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4429706, 34.0576794],
      },
      properties: {
        'Event #': 2023009585,
        DATE: '2/21/23',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'THE MAJESTIC CREST THEATRE\n 1262 WESTWOOD BLVD.',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0414',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4469309, 34.0611873],
      },
      properties: {
        'Event #': 2023009635,
        DATE: '2/21/23',
        EVENT:
          'BATTERY\n (2) OFFENSIVE WORDS IN PUBLIC PLACE\n (3) WARRANT ARREST',
        CATEGORY: 'ASSAULT/BATTERY\n OTHER/MULTIPLE\n OTHER/MULTIPLE',
        LOCATION: 'WHOLE FOODS\n 1050 GAYLEY AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0415',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4284953, 34.0229563],
      },
      properties: {
        'Event #': 2023009640,
        DATE: '2/21/23',
        EVENT: 'PETTY THEFT - MAIL OR PACKAGE',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'SAWTELLE APARTMENTS\n 3232 SAWTELLE BLVD.',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0416',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.441466, 34.0749691],
      },
      properties: {
        'Event #': 2023009650,
        DATE: '2/21/23',
        EVENT: 'GRAND THEFT AUTO',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'YOUNG RESEARCH LIBRARY\n 280 CHARLES E YOUNG DRIVE N',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '23-0417',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4423308, 34.1481465],
      },
      properties: {
        'Event #': 2023009654,
        DATE: '2/21/23',
        EVENT: 'DCFS REPORT ONLY',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '14200-BLOCK DICKENS STREET',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0418',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4282273, 34.0223773],
      },
      properties: {
        'Event #': 2023009683,
        DATE: '2/21/23',
        EVENT: 'PETTY THEFT - MAIL OR PACKAGE',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'SAWTELLE APARTMENTS\n 3250 SAWTELLE BLVD.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0419',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4410971, 34.0705889],
      },
      properties: {
        'Event #': 2023009709,
        DATE: '2/21/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'KNUDSEN HALL\n 475 PORTOLA PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0420',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4486342, 34.0638872],
      },
      properties: {
        'Event #': 2023009712,
        DATE: '2/21/23',
        EVENT: 'ARSON - PROPERTY',
        CATEGORY: 'ARSON',
        LOCATION: 'GAYLEY HEIGHTS APARTMENTS\n 10995 LE CONTE AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0421',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4388979, 34.074164],
      },
      properties: {
        'Event #': 2023009720,
        DATE: '2/21/23',
        EVENT: 'GRAND THEFT - BICYCLES',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'PUBLIC AFFAIRS BUILDING\n 337 CHARLES E YOUNG DRIVE E',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '23-0423',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4486342, 34.0638872],
      },
      properties: {
        'Event #': 2023009721,
        DATE: '2/21/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'GAYLEY HEIGHTS APARTMENTS\n 10995 LE CONTE AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0424',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4400147, 34.0711317],
      },
      properties: {
        'Event #': 2023009722,
        DATE: '2/21/23',
        EVENT: 'PETTY THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'SCHOENBERG MUSIC BUILDING\n 445 CHARLES E. YOUNG DRIVE EAST',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0425',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4395835, 34.0666508],
      },
      properties: {
        'Event #': 2023009723,
        DATE: '2/21/23',
        EVENT: 'BATTERY',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: '798 HILGARD AVE./MANNING AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0426',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4528034, 34.0674707],
      },
      properties: {
        'Event #': 2023009747,
        DATE: '2/21/23',
        EVENT:
          'IMPERSONATE WITHOUT CONSENT - HARM/DEFRAUD/ETC - INT ERNET WEBSTE',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '527 MIDVALE APARTMENTS\n 527 MIDVALE AVE.',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0427',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4866355, 34.0274739],
      },
      properties: {
        'Event #': 2023009864,
        DATE: '2/22/23',
        EVENT: 'PETTY THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'UCLA SANTA MONICA HOSPITAL\n 1250 16TH ST.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0432',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4441451, 34.070418],
      },
      properties: {
        'Event #': 2023009876,
        DATE: '2/22/23',
        EVENT: 'PETTY THEFT - SHOPLIFTING',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'ACKERMAN UNION\n 308 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0433',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4532588, 34.0705355],
      },
      properties: {
        'Event #': 2023009880,
        DATE: '2/22/23',
        EVENT: 'TRAFFIC COLLISION REPORT',
        CATEGORY: 'TRAFFIC/VEHICULAR',
        LOCATION: '449 GAYLEY AVE./LANDFAIR AVE.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '23-0435',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4467431, 34.062413],
      },
      properties: {
        'Event #': 2023009903,
        DATE: '2/22/23',
        EVENT: 'PETTY THEFT - MAIL OR PACKAGE',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '10944 WEYBURN AVE.',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0436',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.442553, 34.0696278],
      },
      properties: {
        'Event #': 2023009924,
        DATE: '2/22/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'MATHEMATICAL SCIENCES BUILDING\n 520 PORTOLA PLAZA',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0438',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4468214, 34.05948109],
      },
      properties: {
        'Event #': 2023009932,
        DATE: '2/22/23',
        EVENT:
          'PETTY THEFT - BICYCLES\n (2) POSSESS CONTROLLED SUBSTANCE\n (3) PARAPHERNALIA - POSSESS UNLAWFUL\n (4) POSSESS/ETC BURGLARY TOOLS',
        CATEGORY:
          'THEFT/BURGLARY\n DRUG/CONTROLLED SUBSTANCE\n DRUG/CONTROLLED SUBSTANCE\n THEFT/BURGLARY',
        LOCATION: '11000 KINROSS AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0439',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4530909, 34.0715897],
      },
      properties: {
        'Event #': 2023009949,
        DATE: '2/22/23',
        EVENT: 'PETTY THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'SAXON SUITES\n 325 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0440',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4515229, 34.0716817],
      },
      properties: {
        'Event #': 2023009953,
        DATE: '2/23/23',
        EVENT: 'ATTEMPTED EXTORTION',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'RIEBER HALL\n 310 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0442',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.444123, 34.075333],
      },
      properties: {
        'Event #': 2023010029,
        DATE: '2/23/23',
        EVENT: 'TRAFFIC COLLISION REPORT',
        CATEGORY: 'TRAFFIC/VEHICULAR',
        LOCATION:
          'UNIV ELEMENTARY SCHOOL LAB SCHOOL 1\n 330 CHARLES E YOUNG DRIVE N',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '23-0443',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4515833, 34.0693741],
      },
      properties: {
        'Event #': 2023010043,
        DATE: '2/23/23',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'WESTWOOD CHATEAU APARTMENTS\n 456 LANDFAIR AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0444',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4716812, 33.9990377],
      },
      properties: {
        'Event #': 2023010085,
        DATE: '2/23/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'VFC - FREDERICK R. WEISMAN FAMILY CENTER\n 604 ROSE AVE.',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0445',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.443567, 34.073954],
      },
      properties: {
        'Event #': 2023010112,
        DATE: '2/23/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'ANDERSON SCHOOL OF MANAGEMENT\n 110 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0447',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4523556, 34.0734882],
      },
      properties: {
        'Event #': 2023010187,
        DATE: '2/23/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'HEDRICK HALL\n 250 DE NEVE DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0449',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4499459, 34.0625321],
      },
      properties: {
        'Event #': 2023010188,
        DATE: '2/23/23',
        EVENT: 'PETTY THEFT - BICYCLES\n (2) VANDALISM - DEFACE PROPERTY',
        CATEGORY: 'THEFT/BURGLARY\n VANDALISM',
        LOCATION: 'LAUREL\n 920 WEYBURN PLACE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0451',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4523556, 34.0734882],
      },
      properties: {
        'Event #': 2023010211,
        DATE: '2/24/23',
        EVENT: 'TRESPASS - REFUSE TO LEAVE PROPERTY',
        CATEGORY: 'TRESPASSING',
        LOCATION: 'HEDRICK HALL\n 250 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0450',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4056305, 34.0200141],
      },
      properties: {
        'Event #': 2023010453,
        DATE: '2/24/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'MENTONE APARTMENTS\n 3777 MENTONE AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0454',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4431977, 34.0691706],
      },
      properties: {
        'Event #': 2023010475,
        DATE: '2/24/23',
        EVENT: 'OBTAIN MONEY/ETC BY FALSE PRETENSES (OVER $950)',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'UCLA\n 405 HILGARD AVE.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '23-0455',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4545311, 34.0679209],
      },
      properties: {
        'Event #': 2023010674,
        DATE: '2/25/23',
        EVENT: 'GRAND THEFT - OTHER',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '512 VETERAN APARTMENTS\n 512 VETERAN AVE.',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '23-0458',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4403265, 34.0685617],
      },
      properties: {
        'Event #': 2023010901,
        DATE: '2/26/23',
        EVENT: 'TAMPER WITH VEHICLE',
        CATEGORY: 'VANDALISM',
        LOCATION: '610 CHARLES E YOUNG DRIVE EAST',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0461',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4477465, 34.0599645],
      },
      properties: {
        'Event #': 2023010976,
        DATE: '2/27/23',
        EVENT: 'PEDESTRIAN STOP',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'PARKING STRUCTURE 32\n 1070 VETERAN AVE.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '23-0462',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4490299, 34.0621787],
      },
      properties: {
        'Event #': 2023011024,
        DATE: '2/27/23',
        EVENT: 'PETTY THEFT - BICYCLES',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'WEYBURN TERRACE APARTMENTS\n 925 WEYBURN PLACE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0463',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4399532, 34.0771178],
      },
      properties: {
        'Event #': 2023011044,
        DATE: '2/27/23',
        EVENT: 'GRAND THEFT - MOTOR VEH PARTS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'PARKING STRUCTURE 3\n 215 CHARLES E YOUNG DRIVE N',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '23-0464',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4479294, 34.0651113],
      },
      properties: {
        'Event #': 2023011081,
        DATE: '2/27/23',
        EVENT: 'TAMPER WITH VEHICLE',
        CATEGORY: 'VANDALISM',
        LOCATION: 'PARKING STRUCTURE 1\n 720 GAYLEY AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0466',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4499786, 34.0729953],
      },
      properties: {
        'Event #': 2023011095,
        DATE: '2/27/23',
        EVENT: 'THEFT BY USE OF ACCESS CARD INFORMATION',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '330 DE NEVE DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0470',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4466512, 34.0652918],
      },
      properties: {
        'Event #': 2023011176,
        DATE: '2/28/23',
        EVENT: 'BATTERY',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: 'RONALD REAGAN UCLA MEDICAL CENTER\n 757 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0471',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4401988, 34.0692348],
      },
      properties: {
        'Event #': 2023011277,
        DATE: '2/28/23',
        EVENT: 'GRAND THEFT - OTHER',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'PARKING STRUCTURE 2\n 602 CHARLES E YOUNG DRIVE E',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '23-0472',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4494253, 34.0633376],
      },
      properties: {
        'Event #': 2023011278,
        DATE: '2/28/23',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'LEVERING TERRACE\n 885 LEVERING AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '23-0473',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4413024, 34.0736717],
      },
      properties: {
        'Event #': 2023011290,
        DATE: '2/28/23',
        EVENT: 'PETTY THEFT REPORT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'CAMPBELL HALL\n 335 PORTOLA PLAZA',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '23-0474',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4453406, 34.0715641],
      },
      properties: {
        'Event #': 2023011317,
        DATE: '2/28/23',
        EVENT: 'GRAND THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'WOODEN CENTER\n 221 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '23-0475',
      },
    },
  ],
};
