const MARCH_2024_crimes_geojson = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4416432, 34.0443291],
      },
      properties: {
        'Event #': 2024011993,
        DATE: '3/1/2024',
        EVENT:
          'POSSESS CONTROLLED SUBSTANCE\n(2) PARAPHERNALIA - POSSESS UNLAWFUL',
        CATEGORY: 'DRUG/CONTROLLED SUBSTANCE\nDRUG/CONTROLLED SUBSTANCE',
        LOCATION: '11100 MISSOURI AVE./PONTIUS AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0440',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4486342, 34.0638872],
      },
      properties: {
        'Event #': 2024012086,
        DATE: '3/1/2024',
        EVENT: 'INDECENT EXPOSURE',
        CATEGORY: 'RAPE/OTHER SEX CRIME',
        LOCATION: 'GAYLEY HEIGHTS APARTMENTS\n10995 LE CONTE AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0441',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.446351, 34.066399],
      },
      properties: {
        'Event #': 2024012258,
        DATE: '3/2/2024',
        EVENT: 'ASSAULT',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: 'RONALD REAGAN UCLA MEDICAL CENTER\n757 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0446',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4505217, 34.0628528],
      },
      properties: {
        'Event #': 2024012284,
        DATE: '3/2/2024',
        EVENT: 'UNAUTHORIZED ENTRY OF DWELLING',
        CATEGORY: 'TRESPASSING',
        LOCATION: 'PALO VERDE\n910 WEYBURN PLACE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0447',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4525197, 34.073962],
      },
      properties: {
        'Event #': 2024012450,
        DATE: '3/3/2024',
        EVENT: 'UNAUTHORIZED ENTRY OF DWELLING',
        CATEGORY: 'TRESPASSING',
        LOCATION: '240 DE NEVE DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0450',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4505217, 34.0628528],
      },
      properties: {
        'Event #': 2024012475,
        DATE: '3/3/2024',
        EVENT:
          'UNAUTHORIZED ENTRY OF DWELLING\n(2) CA REGS - NON-AFFILIATE CONSUME ALCOHOL',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'PALO VERDE\n910 WEYBURN PLACE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0451',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4470715, 34.0636598],
      },
      properties: {
        'Event #': 2024012509,
        DATE: '3/4/2024',
        EVENT:
          'POSSESS NARCOTIC CONTROLLED SUBSTANCE\n(2) PARAPHERNALIA - POSSESS UNLAWFUL',
        CATEGORY: 'DRUG/CONTROLLED SUBSTANCE\nDRUG/CONTROLLED SUBSTANCE',
        LOCATION: 'BROXTON AVE. AND LE CONTE AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0454',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4465738, 34.0664764],
      },
      properties: {
        'Event #': 2024012625,
        DATE: '3/4/2024',
        EVENT: 'BURGLARY - FROM MOTOR VEHICLE\n(2) GRAND THEFT - AUTO',
        CATEGORY: 'THEFT/BURGLARY\nTHEFT/BURGLARY',
        LOCATION: '757 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0458',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4613915, 34.0474942],
      },
      properties: {
        'Event #': 2024012644,
        DATE: '3/4/2024',
        EVENT: 'CONTEMPT OF COURT - VIOLATE PROTECTIVE ORDER/ETC',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '11750 WILSHIRE BLVD.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0462',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4486342, 34.0638872],
      },
      properties: {
        'Event #': 2024012673,
        DATE: '3/4/2024',
        EVENT: 'PETTY THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'GAYLEY HEIGHTS APARTMENTS\n10995 LE CONTE AVE.',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0464',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4525558, 34.0639191],
      },
      properties: {
        'Event #': 2024012686,
        DATE: '3/5/2024',
        EVENT: 'VANDALISM ($400 OR MORE)',
        CATEGORY: 'VANDALISM',
        LOCATION: '11090 STRATHMORE DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0465',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4519937, 34.0700609],
      },
      properties: {
        'Event #': 2024012730,
        DATE: '3/5/2024',
        EVENT: 'PETTY THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'WESTWOOD PALM APARTMENTS\n475 GAYLEY AVE.',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0467',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4510504, 34.0729717],
      },
      properties: {
        'Event #': 2024012753,
        DATE: '3/5/2024',
        EVENT: 'LOST PROPERTY REPORT',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'DELTA TERRACE\n330 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0468',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4445256, 34.0694996],
      },
      properties: {
        'Event #': 2024012768,
        DATE: '3/5/2024',
        EVENT: 'GRAND THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'ENGINEERING 6\n404 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '24-0469',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4453406, 34.0715641],
      },
      properties: {
        'Event #': 2024012809,
        DATE: '3/5/2024',
        EVENT: 'PETTY THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'WOODEN CENTER\n221 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0470',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4420203, 34.0722226],
      },
      properties: {
        'Event #': 2024012832,
        DATE: '3/5/2024',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '10740 DICKSON PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0471',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4523556, 34.0734882],
      },
      properties: {
        'Event #': 2024012868,
        DATE: '3/5/2024',
        EVENT: 'INVADE PRIVACY - ELEC TRACK DEVICE',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'HEDRICK HALL\n250 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0472',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4410474, 34.0756937],
      },
      properties: {
        'Event #': 2024012899,
        DATE: '3/6/2024',
        EVENT: 'GRAND THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'BROAD ART CENTER\n240 CHARLES E YOUNG DRIVE N',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0474',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4515833, 34.0693741],
      },
      properties: {
        'Event #': 2024012902,
        DATE: '3/6/2024',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'WESTWOOD CHATEAU APARTMENTS\n456 LANDFAIR AVE.',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0476',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4457535, 34.0606793],
      },
      properties: {
        'Event #': 2024012908,
        DATE: '3/6/2024',
        EVENT: 'MANUFACTURE/SALE/POSSESS/ETC METAL KNUCKLES',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '10900-BLOCK KINROSS AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0475',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4447968, 34.0726364],
      },
      properties: {
        'Event #': 2024012925,
        DATE: '3/6/2024',
        EVENT: 'DUI ALCOHOL\n(2) DUI ALCOHOL/0.08 PERCENT',
        CATEGORY: 'TRAFFIC/VEHICULAR\nTRAFFIC/VEHICULAR',
        LOCATION: 'PARKING STRUCTURE 4\n219 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0477',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4515833, 34.0693741],
      },
      properties: {
        'Event #': 2024012975,
        DATE: '3/6/2024',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'WESTWOOD CHATEAU APARTMENTS\n456 LANDFAIR AVE.',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0479',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.446351, 34.066399],
      },
      properties: {
        'Event #': 2024013135,
        DATE: '3/7/2024',
        EVENT: 'PETTY THEFT - OTHER',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'RONALD REAGAN UCLA MEDICAL CENTER\n757 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0482',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4399532, 34.0771178],
      },
      properties: {
        'Event #': 2024013178,
        DATE: '3/7/2024',
        EVENT: 'BURGLARY - FROM MOTOR VEHICLE',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'PARKING STRUCTURE 3\n215 CHARLES E YOUNG DRIVE N',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0484',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4866355, 34.0274739],
      },
      properties: {
        'Event #': 2024013193,
        DATE: '3/7/2024',
        EVENT: 'THREATEN CRIME W/INTENT TO TERRORIZE',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'UCLA SANTA MONICA HOSPITAL\n1250 16TH ST.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0485',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4383815, 34.0738271],
      },
      properties: {
        'Event #': 2024013200,
        DATE: '3/7/2024',
        EVENT: 'TRAFFIC COLLISION REPORT',
        CATEGORY: 'TRAFFIC/VEHICULAR',
        LOCATION: '350 CHARLES E YOUNG DRIVE E/WYTON DRIVE',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0486',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4477101, 34.0668566],
      },
      properties: {
        'Event #': 2024013355,
        DATE: '3/8/2024',
        EVENT:
          'WARRANT ARREST\n(2) WARRANT ARREST\n(3) DRIVE W/LICENSE SUSPENDED/REVOKED FOR DRUNK/REFUSE CHEM TEST',
        CATEGORY: 'OTHER/MULTIPLE\nOTHER/MULTIPLE\nTRAFFIC/VEHICULAR',
        LOCATION: 'CHARLES E YOUNG DRIVE S/GAYLEY AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0487',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4624439, 33.9987414],
      },
      properties: {
        'Event #': 2024013393,
        DATE: '3/8/2024',
        EVENT:
          'PARAPHERNALIA - POSSESS UNLAWFUL\n(2) OBSTRUCT/RESIST/ETC PUBLIC/P OFFICER/EMT',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '862 LINCOLN BLVD./BROOKS AVE.',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0489',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4518017, 34.067894],
      },
      properties: {
        'Event #': 2024013414,
        DATE: '3/8/2024',
        EVENT: 'INDECENT EXPOSURE',
        CATEGORY: 'RAPE/OTHER SEX CRIME',
        LOCATION: 'GLENROCK REGENCY APARTMENTS\n507 GLENROCK AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0490',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4547114, 34.0668351],
      },
      properties: {
        'Event #': 2024013415,
        DATE: '3/8/2024',
        EVENT: 'COMMIT MAIL THEFT\n(2) VEHICLE TOW REPORT',
        CATEGORY: 'THEFT/BURGLARY\nTRAFFIC/VEHICULAR',
        LOCATION: '599 VETERAN AVE./LEVERING AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0491',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4501049, 34.0704957],
      },
      properties: {
        'Event #': 2024013453,
        DATE: '3/8/2024',
        EVENT: 'TRAFFIC COLLISION OPEN VEHICLE',
        CATEGORY: 'TRAFFIC/VEHICULAR',
        LOCATION: 'DE NEVE PLAZA\n351 CHARLES E YOUNG DRIVE W',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0492',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4452612, 34.0649793],
      },
      properties: {
        'Event #': 2024013501,
        DATE: '3/8/2024',
        EVENT: 'BURGLARY - FROM MOTOR VEHICLE',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'PARKING STRUCTURE 18\n820 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0494',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4447968, 34.0726364],
      },
      properties: {
        'Event #': 2024013571,
        DATE: '3/9/2024',
        EVENT: 'GRAND THEFT - FROM MOTOR VEHICLE',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'PARKING STRUCTURE 4\n219 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0496',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4866355, 34.0274739],
      },
      properties: {
        'Event #': 2024013573,
        DATE: '3/9/2024',
        EVENT: 'TRESPASS - REFUSE TO LEAVE PROPERTY',
        CATEGORY: 'TRESPASSING',
        LOCATION: 'UCLA SANTA MONICA HOSPITAL\n1250 16TH ST.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0495',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4451436, 34.0635092],
      },
      properties: {
        'Event #': 2024013658,
        DATE: '3/9/2024',
        EVENT: 'TRANSIENT FAILS TO REGISTER WHEN RELEASED FROM CUSTODY',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'CHICK-FIL-A\n900 WESTWOOD BLVD.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0499',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4447794, 34.0667059],
      },
      properties: {
        'Event #': 2024013810,
        DATE: '3/10/2024',
        EVENT: 'RAPE - VICTIM UNCONSC OF ACT',
        CATEGORY: 'RAPE/OTHER SEX CRIME',
        LOCATION: '700-BLOCK WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0502',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4465738, 34.0664764],
      },
      properties: {
        'Event #': 2024013945,
        DATE: '3/10/2024',
        EVENT:
          'POSSESS CONTROLLED SUBSTANCE\n(2) PARAPHERNALIA - POSSESS UNLAWFUL',
        CATEGORY: 'DRUG/CONTROLLED SUBSTANCE\nDRUG/CONTROLLED SUBSTANCE',
        LOCATION: 'RRMC ER\n757 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0505',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4400147, 34.0711317],
      },
      properties: {
        'Event #': 2024013961,
        DATE: '3/11/2024',
        EVENT: 'THEFT UTIL SRVS W/O CNSNT\n(2) CA REGS - VIOLATE CURFEW',
        CATEGORY: 'THEFT/BURGLARY\nOTHER/MULTIPLE',
        LOCATION: 'SCHOENBERG MUSIC BUILDING\n445 CHARLES E. YOUNG DR. E.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0507',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4499786, 34.0729953],
      },
      properties: {
        'Event #': 2024014016,
        DATE: '3/11/2024',
        EVENT: 'PETTY THEFT - MAIL OR PACKAGE',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '330 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '24-0508',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.445055, 34.063247],
      },
      properties: {
        'Event #': 2024014032,
        DATE: '3/11/2024',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'WESTWOOD PLAZA BUILDING\n924 WESTWOOD BLVD.',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0509',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4407481, 34.0642796],
      },
      properties: {
        'Event #': 2024014053,
        DATE: '3/11/2024',
        EVENT: 'BURGLARY - FROM MOTOR VEHICLE',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '888 HILGARD AVE.',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0510',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4504663, 34.0685132],
      },
      properties: {
        'Event #': 2024014158,
        DATE: '3/12/2024',
        EVENT: 'ANNOYING COMM - OBSCENE/THREATENING',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'LANDFAIR VISTA\n510 LANDFAIR AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0512',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.446351, 34.066399],
      },
      properties: {
        'Event #': 2024014199,
        DATE: '3/12/2024',
        EVENT: 'SEX PENETRATION - FOREIGN OBJECT/ETC - VICTIM DRUGGED/ETC',
        CATEGORY: 'RAPE/OTHER SEX CRIME',
        LOCATION: 'RONALD REAGAN UCLA MEDICAL CENTER\n700-BLOCK WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0513',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4531568, 34.0650705],
      },
      properties: {
        'Event #': 2024014271,
        DATE: '3/12/2024',
        EVENT: 'PETTY THEFT - BICYCLES',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '655 KELTON AVE.',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0518',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4453406, 34.0715641],
      },
      properties: {
        'Event #': 2024014311,
        DATE: '3/12/2024',
        EVENT: 'PETTY THEFT - OTHER',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'WOODEN CENTER\n221 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0519',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4461552, 34.0672582],
      },
      properties: {
        'Event #': 2024014376,
        DATE: '3/13/2024',
        EVENT: 'CA REGS - VIOLATE CURFEW',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '731 CHARLES E YOUNG DRIVE S',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0521',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.442553, 34.0696278],
      },
      properties: {
        'Event #': 2024014415,
        DATE: '3/13/2024',
        EVENT: 'GRAND THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'MATHEMATICAL SCIENCES BUILDING\n520 PORTOLA PLAZA',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0522',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4515229, 34.0716817],
      },
      properties: {
        'Event #': 2024014442,
        DATE: '3/13/2024',
        EVENT: 'PETTY THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'RIEBER HALL\n310 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0523',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4498788, 34.0717948],
      },
      properties: {
        'Event #': 2024014484,
        DATE: '3/13/2024',
        EVENT: 'PETTY THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'BRUIN PLATE\n350 CHARLES E YOUNG DRIVE W',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0524',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4496167, 34.0738545],
      },
      properties: {
        'Event #': 2024014564,
        DATE: '3/13/2024',
        EVENT: 'SODOMY - VICTIM UNCONSCIOUS OF THE NATURE OF THE ACT',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '200-BLOCK DE NEVE DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0527',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4523556, 34.0734882],
      },
      properties: {
        'Event #': 2024014698,
        DATE: '3/14/2024',
        EVENT: 'PETTY THEFT - OTHER',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'HEDRICK HALL\n250 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '24-0532',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4287779, 34.0237236],
      },
      properties: {
        'Event #': 2024014821,
        DATE: '3/15/2024',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'MAIN OFFICE SAWTELLE APTS\n3200 SAWTELLE BLVD.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0535',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4419627, 34.0661155],
      },
      properties: {
        'Event #': 2024014843,
        DATE: '3/15/2024',
        EVENT: 'GRAND THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'SCHOOL OF DENTISTRY\n714 TIVERTON DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0536',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4453406, 34.0715641],
      },
      properties: {
        'Event #': 2024014913,
        DATE: '3/15/2024',
        EVENT: 'GRAND THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'WOODEN CENTER\n221 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0537',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.443567, 34.073954],
      },
      properties: {
        'Event #': 2024014931,
        DATE: '3/15/2024',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'ANDERSON SCHOOL OF MANAGEMENT\n110 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0538',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4418704, 34.0660174],
      },
      properties: {
        'Event #': 2024014960,
        DATE: '3/15/2024',
        EVENT: 'PETTY THEFT - OTHER',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'SCHOOL OF DENTISTRY\n714 TIVERTON AVE.',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0539',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.446351, 34.066399],
      },
      properties: {
        'Event #': 2024014962,
        DATE: '3/15/2024',
        EVENT:
          'TRESPASS - REFUSE TO LEAVE PROPERTY\n(2) OBSTRUCT/RESIST/ETC PUBLIC/P OFFICER/EMT',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'RONALD REAGAN UCLA MEDICAL CENTER\n757 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0540',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.418866, 34.0590031],
      },
      properties: {
        'Event #': 2024014969,
        DATE: '3/15/2024',
        EVENT: 'RECEIVE/ETC KNOWN STOLEN PROPERTY\n(2) WARRANT ARREST',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '10250 SANTA MONICA BLVD.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0542',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4449232, 34.0628113],
      },
      properties: {
        'Event #': 2024014986,
        DATE: '3/15/2024',
        EVENT:
          'POSSESS NARCOTIC CONTROLLED SUBSTANCE\n(2) PARAPHERNALIA - POSSESS UNLAWFUL\n(3) GIVE FALSE INFORMATION TO PEACE OFFICER\n(4) WARRANT ARREST',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '924 WESTWOOD BLVD.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0543',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4441726, 34.0704554],
      },
      properties: {
        'Event #': 2024015063,
        DATE: '3/16/2024',
        EVENT: 'PETTY THEFT - SHOPLIFTING\n(2) WARRANT ARREST',
        CATEGORY: 'THEFT/BURGLARY\nOTHER/MULTIPLE',
        LOCATION: 'ACKERMAN UNION\n308 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0544',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4469309, 34.0611873],
      },
      properties: {
        'Event #': 2024015216,
        DATE: '3/17/2024',
        EVENT:
          'POSSESS NARCOTIC CONTROLLED SUBSTANCE\n(2) CONTRIBUTE TO THE DELINQUENCY OF A MINOR\n(3) -18 POSSESS MJ FOR SALE',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'WHOLE FOODS\n1050 GAYLEY AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0545',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4506105, 34.0668019],
      },
      properties: {
        'Event #': 2024015341,
        DATE: '3/18/2024',
        EVENT: 'BATTERY - SPOUSE/EX SPOUSE/DATE/ETC',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: 'GLENROCK APARTMENTS 558\n558 GLENROCK AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0549',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4410474, 34.0756937],
      },
      properties: {
        'Event #': 2024015364,
        DATE: '3/18/2024',
        EVENT:
          'ROBBERY\n(2) GIVE FALSE IDENTIFICATION TO PO\n(3) TRANSIENT FAIL 30 DAY UPDATE OF REGISTRATION\n(4) WARRANT ARREST',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '240 CHARLES E YOUNG DRIVE N',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0550',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4441726, 34.0704554],
      },
      properties: {
        'Event #': 2024015418,
        DATE: '3/18/2024',
        EVENT: 'PETTY THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'ACKERMAN UNION\n308 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0552',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4449102, 34.0658188],
      },
      properties: {
        'Event #': 2024015680,
        DATE: '3/19/2024',
        EVENT: 'PETTY THEFT REPORT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'SEMEL INSTITUTE\n760 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0556',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4431252, 34.0592649],
      },
      properties: {
        'Event #': 2024015705,
        DATE: '3/19/2024',
        EVENT:
          'OBSTRUCT/RESIST EXEC OFCR\n(2) ASSAULT ON PEACE OFFICER/FIREFIGHTERS/ETC\n(3) THREATEN CRIME W/INTENT TO TERRORIZE',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'HAMMER MUSEUM\n10889 WILSHIRE BLVD.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0557',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4853841, 34.0274927],
      },
      properties: {
        'Event #': 2024015782,
        DATE: '3/20/2024',
        EVENT: 'LOST PROPERTY',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'SANTA MONICA MEDICAL BUILDING\n1245 16TH ST.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0558',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4545053, 34.0692756],
      },
      properties: {
        'Event #': 2024015835,
        DATE: '3/20/2024',
        EVENT: 'ACCESS COMPUTER/ALTER/ETC DATA - DEVISE SCHEME/ETC DEFRAUD/ETC',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '424 VETERAN AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0559',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.447346, 34.062529],
      },
      properties: {
        'Event #': 2024015901,
        DATE: '3/20/2024',
        EVENT:
          'BATTERY ON PEACE OFFICER/EMERGENCY PERSONNEL/ETC\n(2) MENTAL DISORDER 72 HR OBSERVATION',
        CATEGORY: 'ASSAULT/BATTERY\nOTHER/MULTIPLE',
        LOCATION: 'STARBUCKS\n10955 WEYBURN AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0560',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4466021, 34.06879197],
      },
      properties: {
        'Event #': 2024015939,
        DATE: '3/21/2024',
        EVENT: 'TRAFFIC COLLISION INJURIES',
        CATEGORY: 'TRAFFIC/VEHICULAR',
        LOCATION: 'STRATHMORE UNDERPASS\n142 STRATHMORE PLACE',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0561',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4447968, 34.0726364],
      },
      properties: {
        'Event #': 2024015947,
        DATE: '3/21/2024',
        EVENT: 'BURGLARY - FROM MOTOR VEHICLE',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'PARKING STRUCTURE 4\n219 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED / INACTIVE: NO LEADS',
        'Case #': '24-0562',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4499735, 34.0729973],
      },
      properties: {
        'Event #': 2024015970,
        DATE: '3/21/2024',
        EVENT: 'DUI ALCOHOL\n(2) OBSTRUCT/RESIST/ETC PUBLIC/P OFFICER/EMT',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'COVEL COMMONS\n330 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0563',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4282365, 34.0226469],
      },
      properties: {
        'Event #': 2024016026,
        DATE: '3/21/2024',
        EVENT: 'PETTY THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'SAWTELLE APARTMENTS\n3240 SAWTELLE BLVD.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0564',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.48775, 34.0250503],
      },
      properties: {
        'Event #': 2024016135,
        DATE: '3/21/2024',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '1311 ARIZONA AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0567',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4386278, 34.0593106],
      },
      properties: {
        'Event #': 2024016225,
        DATE: '3/22/2024',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '10777 ASHTON AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0570',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4469294, 34.0703423],
      },
      properties: {
        'Event #': 2024016408,
        DATE: '3/23/2024',
        EVENT: 'SEX REGISTRANT FAIL REPORT ADDRESS CHANGE',
        CATEGORY: 'RAPE/OTHER SEX CRIME',
        LOCATION: 'PAULEY PAVILION\n301 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0572',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4545233, 34.068961],
      },
      properties: {
        'Event #': 2024016712,
        DATE: '3/25/2024',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '440 VETERAN AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0575',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.446351, 34.066399],
      },
      properties: {
        'Event #': 2024016728,
        DATE: '3/25/2024',
        EVENT: 'ANNOYING COMM - OBSCENE/THREATENING',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'RONALD REAGAN UCLA MEDICAL CENTER\n757 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0576',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4489671, 34.068547],
      },
      properties: {
        'Event #': 2024016883,
        DATE: '3/26/2024',
        EVENT: 'TRAFFIC COLLIS UNIVERSITY VEH',
        CATEGORY: 'TRAFFIC/VEHICULAR',
        LOCATION: 'GAYLEY AVE./STRATHMORE DRIVE',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0578',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4528034, 34.0674707],
      },
      properties: {
        'Event #': 2024016961,
        DATE: '3/26/2024',
        EVENT: 'BURGLARY - FROM MOTOR VEHICLE',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '527 MIDVALE APARTMENTS\n527 MIDVALE AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0580',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.48826, 34.03372121],
      },
      properties: {
        'Event #': 2024016966,
        DATE: '3/26/2024',
        EVENT: 'IDENTITY THEFT - GET CREDIT/ETC OTHER`S ID',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '953 18TH ST.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0581',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.448054, 34.0604573],
      },
      properties: {
        'Event #': 2024017050,
        DATE: '3/27/2024',
        EVENT: 'CA REGS - VIOLATE CURFEW',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'WEST MEDICAL BUILDING\n1010 VETERAN AVE.',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0583',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4432392, 34.0692388],
      },
      properties: {
        'Event #': 2024017092,
        DATE: '3/27/2024',
        EVENT:
          'GRAND THEFT - FROM BUILDINGS\n(2) TRESPASS - OCCUPY PROPERTY WITHOUT CONSENT',
        CATEGORY: 'THEFT/BURGLARY\nTRESPASSING',
        LOCATION: 'BOELTER HALL\n580 PORTOLA PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0584',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4436004, 34.0704371],
      },
      properties: {
        'Event #': 2024017205,
        DATE: '3/27/2024',
        EVENT: 'BATTERY',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: 'KERCKHOFF HALL\n310 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '24-0585',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4463791, 34.0650959],
      },
      properties: {
        'Event #': 2024017217,
        DATE: '3/27/2024',
        EVENT: 'TRESPASS - REFUSE TO LEAVE PROPERTY',
        CATEGORY: 'TRESPASSING',
        LOCATION: 'MEDICAL PLAZA 200 PETER MORTON BUILDING\n200 MEDICAL PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '24-0586',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4412088, 34.0688448],
      },
      properties: {
        'Event #': 2024017238,
        DATE: '3/28/2024',
        EVENT: 'WARRANT ARREST',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'MOLECULAR SCIENCES\n607 CHARLES E YOUNG DRIVE E',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0587',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4864914, 34.0268509],
      },
      properties: {
        'Event #': 2024017239,
        DATE: '3/28/2024',
        EVENT: 'REGISTERED SEX OFFENDER VIOLATE ANY REQUIREMENT',
        CATEGORY: 'RAPE/OTHER SEX CRIME',
        LOCATION: '1225 15TH ST.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0588',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4496915, 34.067988],
      },
      properties: {
        'Event #': 2024017344,
        DATE: '3/28/2024',
        EVENT: 'TAKE VEHICLE W/O OWNER`S CONSENT/VEHICLE THEFT',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'TREEHOUSE\n10919 STRATHMORE DRIVE',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0589',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4477418, 34.0577768],
      },
      properties: {
        'Event #': 2024017410,
        DATE: '3/28/2024',
        EVENT: 'WARRANT ARREST',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '10999 WILSHIRE BLVD./VETERAN AVE.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0590',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.448054, 34.0604573],
      },
      properties: {
        'Event #': 2024017422,
        DATE: '3/29/2024',
        EVENT: 'MISCELLANEOUS INCIDENT REPORT',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'WEST MEDICAL BUILDING\n1010 VETERAN AVE.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0591',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4401988, 34.0692348],
      },
      properties: {
        'Event #': 2024017434,
        DATE: '3/29/2024',
        EVENT: 'CA REGS - VIOLATE CURFEW',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'PARKING STRUCTURE 2\n602 CHARLES E YOUNG DRIVE E',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0592',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4486342, 34.0638872],
      },
      properties: {
        'Event #': 2024017454,
        DATE: '3/29/2024',
        EVENT: 'VANDALISM - DEFACE PROPERTY',
        CATEGORY: 'VANDALISM',
        LOCATION: 'GAYLEY HEIGHTS APARTMENTS\n10995 LE CONTE AVE.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0593',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4454214, 34.0636831],
      },
      properties: {
        'Event #': 2024017526,
        DATE: '3/29/2024',
        EVENT:
          'POSSESS NARCOTIC CONTROLLED SUBSTANCE\n(2) PARAPHERNALIA - POSSESS UNLAWFUL\n(3) WARRANT ARREST',
        CATEGORY:
          'DRUG/CONTROLLED SUBSTANCE\nDRUG/CONTROLLED SUBSTANCE\nOTHER/MULTIPLE',
        LOCATION: '899 WESTWOOD PLAZA/LE CONTE AVE.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0595',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4469534, 34.0640108],
      },
      properties: {
        'Event #': 2024017554,
        DATE: '3/29/2024',
        EVENT: 'CA REGS - BRING/MAINTAIN LARGE PERSONAL BELONGINGS',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '10945 LE CONTE AVE.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0596',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.448893, 34.0465827],
      },
      properties: {
        'Event #': 2024017573,
        DATE: '3/29/2024',
        EVENT: 'POSSESS CONTROLLED SUBSTANCE FOR SALE\n(2) WARRANT ARREST',
        CATEGORY: 'DRUG/CONTROLLED SUBSTANCE\nOTHER/MULTIPLE',
        LOCATION: '11305 SANTA MONICA BLVD.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0597',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4532636, 34.0743018],
      },
      properties: {
        'Event #': 2024017659,
        DATE: '3/30/2024',
        EVENT:
          'POSSESS F/ARM IN SCHL ZN\n(2) CARRY CONCEALED WEAPON IN VEHICLE\n(3) CARRY LOADED FIREARM ON/IN PERSON/VEHICLE - PUBLIC PLACE',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'PARKING STRUCTURE RC\n113 DE NEVE DRIVE',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0599',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [121.0597871, 14.5219678],
      },
      properties: {
        'Event #': 2024017661,
        DATE: '3/30/2024',
        EVENT: 'MENTAL DISORDER 72 HR OBSERVATION',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '1200-BLOCK 16TH ST.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0600',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4266213, 34.0201416],
      },
      properties: {
        'Event #': 2024017675,
        DATE: '3/30/2024',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'SAWTELLE APARTMENTS\n3140 SAWTELLE BLVD.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0601',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4488303, 34.0473996],
      },
      properties: {
        'Event #': 2024017677,
        DATE: '3/30/2024',
        EVENT:
          'POSSESS CONTROLLED SUBSTANCE\n(2) PARAPHERNALIA - POSSESS UNLAWFUL\n(3) TRESPASS - OCCUPY PROPERTY WITHOUT CONSENT\n(4) WARRANT ARREST',
        CATEGORY:
          'DRUG/CONTROLLED SUBSTANCE\nDRUG/CONTROLLED SUBSTANCE\nTRESPASSING\nOTHER/MULTIPLE',
        LOCATION: 'UCLA THRIFT STORE\n11271 MASSACHUSETTS AVE.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0602',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4855122, 34.02688867],
      },
      properties: {
        'Event #': 2024017763,
        DATE: '3/31/2024',
        EVENT: 'SUBJECT REFUSING TO LEAVE',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'SMH ER\n1250 16TH ST.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0603',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4512206, 34.0666857],
      },
      properties: {
        'Event #': 2024017764,
        DATE: '3/31/2024',
        EVENT: 'PETTY THEFT - MAIL OR PACKAGE',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'GLENROCK WEST APARTMENTS\n555 GLENROCK AVE.',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '24-0604',
      },
    },
  ],
};
