var geojsonFeature = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4501344, 34.0703263],
      },
      properties: {
        Name: 'De Neve Commons',
        Address: '351 Charles E. Young Drive West, Los Angeles, CA 90024',
        ConstructionYear: 2002,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: true,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4495632, 34.0714634],
      },
      properties: {
        Name: 'De Neve C',
        Address: '301 Charles E. Young Drive West, Los Angeles, CA 90095',
        ConstructionYear: 2000,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: true,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4495423, 34.0712134],
      },
      properties: {
        Name: 'De Neve D',
        Address: '321 Charles E. Young Drive West, Los Angeles, CA 90024',
        ConstructionYear: 2000,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: true,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4512233, 34.0706705],
      },
      properties: {
        Name: 'De Neve E',
        Address: '331 Charles E. Young Drive West, Los Angeles, CA 90024',
        ConstructionYear: 2000,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: true,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4509723, 34.0702328],
      },
      properties: {
        Name: 'De Neve F',
        Address: '381 Charles E. Young Drive West, Los Angeles, CA 90024',
        ConstructionYear: 2000,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: true,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4418606, 34.0660175],
      },
      properties: {
        Name: 'UCLA School of Dentistry',
        Address: '714 Tiverton Avenue, Los Angeles, CA 90024',
        ConstructionYear: '1966 (North Wing), 1966 (South Wing) ',
        RetrofitYear: '2001 (North Wing), 2017 (South Wing)',
        SeismicRating: 'IV',
        Custom: true,
        RatingText: 'IV (North Wing), III (South Wing)',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4461552, 34.0672582],
      },
      properties: {
        Name: 'Facilities Management Building',
        Address: '731 Charles E. Young Drive South, Los Angeles, CA 90095',
        ConstructionYear:
          '1994 (Building 2), 1994 (Building 3), 1994 (CoGen W Building 1), 1995 (CoGen E Building 5), 1994 (ESB Building 4)',
        RetrofitYear: NaN,
        SeismicRating: 'IV',
        Custom: false,
        RatingText:
          'IV (Building 2), III (Building 3), IV (CoGen W Building 1), III (CoGen E Building 5), III (ESB Building 4)',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4392384, 34.0703209],
      },
      properties: {
        Name: 'Faculty Center',
        Address: '480 Charles E. Young Drive East, Los Angeles, CA 90024',
        ConstructionYear: 1959,
        RetrofitYear: NaN,
        SeismicRating: 'V',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4411305, 34.0668155],
      },
      properties: {
        Name: 'La Kretz Botany Building',
        Address: '618 Charles E. Young Drive South, Los Angeles, CA 90095',
        ConstructionYear: 1959,
        RetrofitYear: NaN,
        SeismicRating: 'V',
        Custom: true,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4387084, 34.0716091],
      },
      properties: {
        Name: 'Murphy Hall',
        Address: '410 Charles E Young Dr E, Los Angeles, CA 90095',
        ConstructionYear: '1937 (Main), 1950 (West), 1964 (East)',
        RetrofitYear: NaN,
        SeismicRating: 'V',
        Custom: true,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4421809, 34.0716126],
      },
      properties: {
        Name: 'Powell Library',
        Address: '10740 Dickson Ct, Los Angeles, CA 90095',
        ConstructionYear: '1930 (Main), 1947 (East Wing)',
        RetrofitYear: '1996 (Main), 1996 (East Wing)',
        SeismicRating: 'V',
        Custom: true,
        RatingText: 'V',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4412792, 34.0696422],
      },
      properties: {
        Name: 'Psychology Tower/Franz Hall',
        Address: '502 Portola Plaza, Los Angeles, CA 90095',
        ConstructionYear: '1965 (Tower), 1960 (1961 Addition)',
        RetrofitYear: NaN,
        SeismicRating: 'V',
        Custom: true,
        RatingText: 'V (Tower), IV (1961 Addition)',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4392242, 34.0741192],
      },
      properties: {
        Name: 'Public Affairs',
        Address: '337 Charles E. Young Drive East, Los Angeles, CA 90095',
        ConstructionYear:
          '1960 (Tower), 1958 (Data Processing Center), 1960 (Arts Library)',
        RetrofitYear: '1997 (Tower)',
        SeismicRating: 'V',
        Custom: true,
        RatingText: 'V',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4448153, 34.0658571],
      },
      properties: {
        Name: 'Semel Institute',
        Address: '760 Westwood Plaza, Los Angeles, CA 90024',
        ConstructionYear: 1961,
        RetrofitYear: NaN,
        SeismicRating: 'V',
        Custom: true,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4510674, 34.0752346],
      },
      properties: {
        Name:
          'Sunset Canyon Recreation Center – Main Office and Conference Center',
        Address: '111 Easton Drive, Los Angeles, CA 90024',
        ConstructionYear: 1965,
        RetrofitYear: NaN,
        SeismicRating: 'IV',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4510674, 34.0752346],
      },
      properties: {
        Name: 'Sunset Canyon Recreation Center – Bueons Ayres Room',
        Address: '111 Easton Drive, Los Angeles, CA 90024',
        ConstructionYear: 1965,
        RetrofitYear: NaN,
        SeismicRating: 'IV',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4510674, 34.0752346],
      },
      properties: {
        Name: 'Sunset Canyon Recreation Center – Santa Fe Room',
        Address: '111 Easton Drive, Los Angeles, CA 90024',
        ConstructionYear: 1965,
        RetrofitYear: NaN,
        SeismicRating: 'V',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4510674, 34.0752346],
      },
      properties: {
        Name: 'Sunset Canyon Recreation Center – Family Pool Restrooms',
        Address: '111 Easton Drive, Los Angeles, CA 90024',
        ConstructionYear: 1965,
        RetrofitYear: NaN,
        SeismicRating: 'IV',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4510674, 34.0752346],
      },
      properties: {
        Name: 'Sunset Canyon Recreation Center – Park Pool Locker Rooms',
        Address: '111 Easton Drive, Los Angeles, CA 90024',
        ConstructionYear: 1965,
        RetrofitYear: NaN,
        SeismicRating: 'IV',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4414615, 34.0749683],
      },
      properties: {
        Name: 'Young Research Library',
        Address: '280 Charles E. Young Drive North, Los Angeles, CA 90095',
        ConstructionYear: 1964,
        RetrofitYear: NaN,
        SeismicRating: 'V',
        Custom: true,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4377362, 34.0746304],
      },
      properties: {
        Name: 'Kneller House',
        Address: '372 Hilgard Avenue, Los Angeles, CA 90024',
        ConstructionYear: 1929,
        RetrofitYear: NaN,
        SeismicRating: 'VI',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4277432, 34.0589192],
      },
      properties: {
        Name: 'Kinnard House',
        Address: '10475 Kinnard Avenue, Los Angeles, CA 90024',
        ConstructionYear: 1961,
        RetrofitYear: NaN,
        SeismicRating: 'V',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4428241, 34.0577424],
      },
      properties: {
        Name: 'UCLA Nimoy Theater',
        Address: '1262 Westwood Boulevard, Los Angeles, CA 90024',
        ConstructionYear: 1940,
        RetrofitYear: NaN,
        SeismicRating: 'VI',
        Custom: true,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4790742, 34.0344154],
      },
      properties: {
        Name: 'UCLA Health Santa Monica Wilshire Immediate Care',
        Address: '2424 Wilshire Boulevard, Santa Monica, CA 90403',
        ConstructionYear: 1948,
        RetrofitYear: 2015,
        SeismicRating: 'IV',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4847104, 34.0305817],
      },
      properties: {
        Name: 'UCLA Health Santa Monica Wilshire Immediate Care',
        Address: '1821 Wilshire Boulevard, Santa Monica, CA 90403',
        ConstructionYear: 1948,
        RetrofitYear: NaN,
        SeismicRating: 'IV',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4850764, 34.0301547],
      },
      properties: {
        Name: 'UCLA Neurology Outpatient Clinic',
        Address: '1801 Wilshire Boulevard, Santa Monica, CA 90403',
        ConstructionYear: 1978,
        RetrofitYear: NaN,
        SeismicRating: 'IV',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.443828, 34.0481354],
      },
      properties: {
        Name: 'UCLA Neurology Outpatient Clinic',
        Address: '11075 Santa Monica Blvd, Los Angeles, CA 90025',
        ConstructionYear: 1980,
        RetrofitYear: NaN,
        SeismicRating: 'IV',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4911884, 34.0252844],
      },
      properties: {
        Name: 'UCLA Spine Center',
        Address: '1131 Wilshire Boulevard, Santa Monica, CA 90403',
        ConstructionYear: 1981,
        RetrofitYear: NaN,
        SeismicRating: 'IV',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4851658, 34.0303862],
      },
      properties: {
        Name: 'UCLA Stein Eye Center',
        Address: '1807 Wilshire Boulevard, Santa Monica, CA 90403',
        ConstructionYear: 1978,
        RetrofitYear: NaN,
        SeismicRating: 'IV',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4269437, 34.0247146],
      },
      properties: {
        Name: 'University Village 3171',
        Address: '3171 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4266699, 34.0242944],
      },
      properties: {
        Name: 'University Village 3181',
        Address: '3181 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4264647, 34.0239343],
      },
      properties: {
        Name: 'University Village 3191',
        Address: '3191 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4276796, 34.0254318],
      },
      properties: {
        Name: 'University Village GRG2',
        Address: '3151 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4263733, 34.0232291],
      },
      properties: {
        Name: 'University Village CCC',
        Address: '3233 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4251049, 34.0226992],
      },
      properties: {
        Name: 'University Village 3281',
        Address: '3281 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1995,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.427888, 34.0222721],
      },
      properties: {
        Name: 'University Village 3260',
        Address: '3260 Sawtelle Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1995,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4276611, 34.0216699],
      },
      properties: {
        Name: 'University Village 3290',
        Address: '3290 Sawtelle Boulevard, Los Angeles, CA 90066',
        ConstructionYear: 1995,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4302294, 34.0254804],
      },
      properties: {
        Name: 'University Village 3100',
        Address: '3100 Sawtelle Boulevard, Los Angeles, CA 90066',
        ConstructionYear: 1995,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4301382, 34.0251034],
      },
      properties: {
        Name: 'University Village 3110',
        Address: '3110 Sawtelle Boulevard, Los Angeles, CA 90066',
        ConstructionYear: 1995,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4299837, 34.02489],
      },
      properties: {
        Name: 'University Village 3120',
        Address: '3120 Sawtelle Boulevard, Los Angeles, CA 90066',
        ConstructionYear: 1995,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4298644, 34.0246922],
      },
      properties: {
        Name: 'University Village 3130',
        Address: '3130 Sawtelle Boulevard, Los Angeles, CA 90066',
        ConstructionYear: 1995,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4295869, 34.0246742],
      },
      properties: {
        Name: 'University Village 3140',
        Address: '3140 Sawtelle Boulevard, Los Angeles, CA 90066',
        ConstructionYear: 1995,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4296226, 34.0243834],
      },
      properties: {
        Name: 'University Village 3150',
        Address: '3150 Sawtelle Boulevard, Los Angeles, CA 90066',
        ConstructionYear: 1995,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4294111, 34.0241594],
      },
      properties: {
        Name: 'University Village 3160',
        Address: '3160 Sawtelle Boulevard, Los Angeles, CA 90066',
        ConstructionYear: 1995,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4291841, 34.0240724],
      },
      properties: {
        Name: 'University Village 3170',
        Address: '3170 Sawtelle Boulevard, Los Angeles, CA 90066',
        ConstructionYear: 1995,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4273187, 34.0253474],
      },
      properties: {
        Name: 'University Village 3155',
        Address: '3155 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4293434, 34.0238852],
      },
      properties: {
        Name: 'University Village 3180',
        Address: '3180 Sawtelle Boulevard, Los Angeles, CA 90066',
        ConstructionYear: 1995,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4287779, 34.0237236],
      },
      properties: {
        Name: 'University Village 3200',
        Address: '3200 Sawtelle Boulevard, Los Angeles, CA 90066',
        ConstructionYear: 1995,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4284953, 34.0229563],
      },
      properties: {
        Name: 'University Village 3232',
        Address: '3232 Sawtelle Boulevard, Los Angeles, CA 90066',
        ConstructionYear: 1995,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4276796, 34.0254318],
      },
      properties: {
        Name: 'University Village 3151',
        Address: '3151 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4258261, 34.0242511],
      },
      properties: {
        Name: 'University Village 3234',
        Address: '3234 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1995,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4272792, 34.0251027],
      },
      properties: {
        Name: 'University Village 3161',
        Address: '3161 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4256659, 34.0228667],
      },
      properties: {
        Name: 'University Village 3241',
        Address: '3241 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4252858, 34.0226508],
      },
      properties: {
        Name: 'University Village 3251',
        Address: '3251 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4251155, 34.022604],
      },
      properties: {
        Name: 'University Village 3255',
        Address: '3255 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4259397, 34.022558],
      },
      properties: {
        Name: 'University Village 3245',
        Address: '3245 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4269044, 34.0237497],
      },
      properties: {
        Name: 'University Village 3195',
        Address: '3195 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4268954, 34.0249808],
      },
      properties: {
        Name: 'University Village 3185',
        Address: '3185 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4267388, 34.0246159],
      },
      properties: {
        Name: 'University Village 3175',
        Address: '3175 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.42707, 34.0250338],
      },
      properties: {
        Name: 'University Village 3165',
        Address: '3165 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4282365, 34.0226469],
      },
      properties: {
        Name: 'University Village 3240',
        Address: '3240 Sawtelle Boulevard, Los Angeles, CA 90066',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.424759, 34.0219324],
      },
      properties: {
        Name: 'University Village 3271',
        Address: '3271 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1995,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4274913, 34.0219285],
      },
      properties: {
        Name: 'University Village 3280',
        Address: '3280 Sawtelle Boulevard, Los Angeles, CA 90066',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4273119, 34.0213308],
      },
      properties: {
        Name: 'University Village 3270',
        Address: '3270 Sawtelle Boulevard, Los Angeles, CA 90066',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4282273, 34.0223773],
      },
      properties: {
        Name: 'University Village 3250',
        Address: '3250 Sawtelle Boulevard, Los Angeles, CA 90066',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4251513, 34.0224823],
      },
      properties: {
        Name: 'University Village 3265',
        Address: '3265 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.425027, 34.0223072],
      },
      properties: {
        Name: 'University Village 3261',
        Address: '3261 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4245022, 34.021499],
      },
      properties: {
        Name: 'University Village 3327',
        Address: '3327 Sepulveda Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 1996,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4273544, 34.021603],
      },
      properties: {
        Name: 'University Village 3300',
        Address: '3300 Sawtelle Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 2003,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4272747, 34.0214148],
      },
      properties: {
        Name: 'University Village 3310',
        Address: '3310 Sawtelle Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 2003,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4271414, 34.0212554],
      },
      properties: {
        Name: 'University Village 3320',
        Address: '3320 Sawtelle Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 2003,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4267328, 34.0207593],
      },
      properties: {
        Name: 'University Village 3340',
        Address: '3340 Sawtelle Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 2003,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4266078, 34.0206192],
      },
      properties: {
        Name: 'University Village 3350',
        Address: '3350 Sawtelle Boulevard, Los Angeles CA 90034',
        ConstructionYear: 2003,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4266612, 34.0204524],
      },
      properties: {
        Name: 'University Village 3360',
        Address: '3360 Sawtelle Boulevard, Los Angeles, CA 90034',
        ConstructionYear: 2003,
        RetrofitYear: NaN,
        SeismicRating: 'III',
        Custom: false,
        RatingText: '',
      },
    },
  ],
};
