let keyword_list = {
    "college":[
       "blah",
       "blah",
       "blah"
    ],
    "immigration":[
       "blah",
       "blah",
       "blah"
    ],
    "mental-health":[
       "blah",
       "blah",
       "blah"
    ],
    "discrimination-and-equality":[
       "blah",
       "blah",
       "blah"
    ],
    "employment":[
       "blah",
       "blah",
       "blah"
    ],
    "healthcare":[
       "blah",
       "blah",
       "blah"
    ],
    "environment":[
       "blah",
       "blah",
       "blah"
    ],
    "women-health":[
       "blah",
       "blah",
       "blah"
    ],
    "marijuana":[
       "blah",
       "blah",
       "blah"
    ],
    "gun-rights":[
       "blah",
       "blah",
       "blah"
    ]
 };