var labels = [
  'Non-Profit',
  'Marketplace',
  'Agency/Coaching',
  'Hard Tech',
  'Consumer Social',
  'VC',
  'Exploring',
  'Consumer SAAS',
  'B2B SAAS',
  'Influencer Marketing',
  'Entertainment',
  'Web3',
  'Ecommerce/CPG',
  'Education',
  'AI/ML',
  'Community ',
  'Computer Science',
  'Computer Science',
  'Computer Science',
  'Computer Science',
  'Computer Science',
  'Computer Science',
  'Philosophy',
  'Psychobiology',
  'Communication',
  'Communication',
  'Communication',
  'Cognitive Science',
  'Cognitive Science',
  'Cognitive Science',
  'Cognitive Science',
  'Cognitive Science',
  'Cognitive Science',
  'Cognitive Science',
  'Cognitive Science',
  'Economics',
  'Economics',
  'Economics',
  'Economics',
  'Economics',
  'Design & Media Arts',
  'Design & Media Arts',
  'Business Economics',
  'Business Economics',
  'History',
  'Film & Television',
  'Film & Television',
  'Film & Television',
  'Framework Design & Social Entrepreneurship',
  'Framework Design & Social Entrepreneurship',
  'Statistics',
  'Political Science & Government',
  'Anderson Venture Accelerator',
  'Anderson Venture Accelerator',
  'School of Dentistry',
  'Engineering',
  'Financial Actuarial Mathematics',
  'Political Science',
  'Political Science',
  'Communication and Media Studies',
  'Communication and Media Studies',
  'Small Business Administration',
  'Management',
  'Math/Econ',
  'Computer Science and Engineering',
  'Computer Science and Engineering',
  'Computer Science and Engineering',
  'Physics',
  'Electrical Engineering',
  'Electrical Engineering',
  'Atmospheric and Oceanic Science',
  'Atmospheric and Oceanic Science',
  'Neuroscience',
  'Business and Economics',
  'Math',
  'Digital Marketing and Data Analytics',
  'Digital Marketing and Data Analytics',
  'Business Administration, Management and Operations',
  'Business Administration, Management and Operations',
  'Business Administration, Management and Operations',
  'Bioengineering',
  'Biomedical Engineering',
  'Biochemistry',
  'Synthetic Biology',
];
var parents = [
  "Startup Industry by Founders' Major",
  "Startup Industry by Founders' Major",
  "Startup Industry by Founders' Major",
  "Startup Industry by Founders' Major",
  "Startup Industry by Founders' Major",
  "Startup Industry by Founders' Major",
  "Startup Industry by Founders' Major",
  "Startup Industry by Founders' Major",
  "Startup Industry by Founders' Major",
  "Startup Industry by Founders' Major",
  "Startup Industry by Founders' Major",
  "Startup Industry by Founders' Major",
  "Startup Industry by Founders' Major",
  "Startup Industry by Founders' Major",
  "Startup Industry by Founders' Major",
  "Startup Industry by Founders' Major",
  'Consumer SAAS',
  'Agency/Coaching',
  'Ecommerce/CPG',
  'Education',
  'VC',
  'Exploring',
  'Ecommerce/CPG',
  'Education',
  'Agency/Coaching',
  'Web3',
  'Non-Profit',
  'B2B SAAS',
  'VC',
  'Hard Tech',
  'Agency/Coaching',
  'Ecommerce/CPG',
  'Consumer SAAS',
  'AI/ML',
  'Consumer Social',
  'Web3',
  'Agency/Coaching',
  'AI/ML',
  'VC',
  'Ecommerce/CPG',
  'Ecommerce/CPG',
  'Agency/Coaching',
  'Community ',
  'Ecommerce/CPG',
  'Agency/Coaching',
  'Consumer Social',
  'Agency/Coaching',
  'Influencer Marketing',
  'VC',
  'Agency/Coaching',
  'VC',
  'Agency/Coaching',
  'Agency/Coaching',
  'AI/ML',
  'Marketplace',
  'Ecommerce/CPG',
  'Community ',
  'B2B SAAS',
  'Community ',
  'Consumer SAAS',
  'Agency/Coaching',
  'B2B SAAS',
  'B2B SAAS',
  'Entertainment',
  'Marketplace',
  'VC',
  'Agency/Coaching',
  'VC',
  'VC',
  'Consumer SAAS',
  'Education',
  'Consumer SAAS',
  'Education',
  'Agency/Coaching',
  'Education',
  'AI/ML',
  'B2B SAAS',
  'AI/ML',
  'B2B SAAS',
  'Agency/Coaching',
  'Hard Tech',
  'Consumer Social',
  'Consumer SAAS',
  'AI/ML',
];
var data = [
  {
    type: 'treemap',
    labels: labels,
    parents: parents,
    values: [
      1,
      2,
      15,
      2,
      4,
      13,
      1,
      6,
      8,
      1,
      2,
      2,
      10,
      7,
      7,
      4,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      3,
      1,
      1,
      2,
      1,
      2,
      1,
      1,
      1,
      1,
      1,
      1,
      2,
      1,
      1,
      1,
      1,
      3,
      1,
      3,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2,
      1,
      1,
      1,
      1,
      2,
      1,
      1,
      1,
      2,
      1,
      1,
      1,
      1,
      2,
      1,
      2,
      2,
      2,
      1,
      2,
      1,
      1,
      1,
      1,
      1,
    ],
    textinfo: 'label+value+percent parent+percent entry',
    insidetextfont: { size: 100 },
    outsidetextfont: { size: 100, color: '#377eb8' },
    marker: { line: { width: 2 } },
    pathbar: { visible: false },
  },
];
var layout = {
  autosize: true,
  height: 900, // Minimum height
  width: 900, // Minimum width
};

var config = {
  responsive: true,
};

Plotly.newPlot('startups-treemap', data, layout, config);
