var labels = [
" Exploring ",
" Ecommerce/CPG ",
" Education ",
" Non-Profit ",
" Web3 ",
" Agency/Coaching ",
" Web3 ",
" Agency/Coaching ",
" Ecommerce/CPG ",
" Ecommerce/CPG ",
" Ecommerce/CPG ",
" Ecommerce/CPG ",
" Agency/Coaching ",
" B2B SAAS ",
" Consumer Social  ",
" Agency/Coaching ",
" Agency/Coaching ",
" VC ",
" VC ",
" VC ",
" VC ",
" VC ",
" VC ",
" VC ",
" VC ",
" AI/ML ",
" Agency/Coaching ",
" AI/ML ",
" Agency/Coaching ",
" Marketplace ",
" Ecommerce/CPG ",
" Ecommerce/CPG ",
" Ecommerce/CPG ",
" Ecommerce/CPG ",
" Consumer Social ",
" Consumer Social ",
" Community  ",
" Agency/Coaching ",
" Community  ",
" Agency/Coaching ",
" Community  ",
" Agency/Coaching ",
" B2B SAAS ",
" B2B SAAS ",
" B2B SAAS ",
" Influencer Marketing ",
" Agency/Coaching ",
" Entertainment ",
" Entertainment ",
" Marketplace ",
" Agency/Coaching ",
" VC ",
" VC ",
" VC ",
" Consumer SAAS ",
" VC ",
" Consumer SAAS ",
" VC ",
" Consumer SAAS ",
" Education ",
" Education ",
" Education ",
" Agency/Coaching ",
" Education ",
" Agency/Coaching ",
" Education ",
" Education ",
" Ecommerce/CPG ",
" AI/ML ",
" AI/ML ",
" AI/ML ",
" AI/ML ",
" B2B SAAS ",
" B2B SAAS ",
" B2B SAAS ",
" B2B SAAS ",
" Agency/Coaching ",
" Consumer SAAS ",
" Consumer SAAS ",
" Hard Tech ",
" Hard Tech ",
" Consumer Social  ",
" Consumer SAAS ",
" AI/ML ",
" Community  "
  ];
  var parents = [" Computer Science ",
  " Philosophy ",
  " Psychobiology ",
  " Communication ",
  " Communication ",
  " Cognitive Science ",
  " Economics ",
  " Design & Media Arts ",
  " Design & Media Arts ",
  " Business Economics ",
  " Cognitive Science ",
  " Business Economics ",
  " History ",
  " Cognitive Science ",
  " Film & Television ",
  " Film & Television ",
  " Framework Design & Social Entrepreneurship ",
  " Framework Design & Social Entrepreneurship ",
  " Framework Design & Social Entrepreneurship ",
  " Framework Design & Social Entrepreneurship ",
  " Economics ",
  " Statistics ",
  " Statistics ",
  " Statistics ",
  " Cognitive Science ",
  " Cognitive Science ",
  " Political Science & Government ",
  " Anderson Venture Accelerator ",
  " Anderson Venture Accelerator ",
  " School of Dentistry ",
  " Computer Science ",
  " Cognitive Science ",
  " Engineering ",
  " Cognitive Science ",
  " Cognitive Science ",
  " Cognitive Science ",
  " Financial Actuarial Mathematics ",
  " Economics ",
  " Political Science ",
  " Economics ",
  " Political Science ",
  " Communication and Media Studies ",
  " Small Business Administration ",
  " Management ",
  " Political Science ",
  " Film & Television ",
  " Communication ",
  " Math/Econ ",
  " Math/Econ ",
  " Computer Science and Engineering ",
  " Computer Science and Engineering ",
  " Computer Science and Engineering ",
  " Physics ",
  " Computer Science ",
  " Electrical Engineering ",
  " Physics ",
  " Computer Science ",
  " Electrical Engineering ",
  " Atmospheric and Oceanic Science ",
  " Atmospheric and Oceanic Science ",
  " Neuroscience ",
  " Neuroscience ",
  " Business and Economics ",
  " Math ",
  " Computer Science ",
  " Math ",
  " Computer Science ",
  " Economics ",
  " Economics ",
  " Digital Marketing and Data Analytics ",
  " Business Administration, Management and Operations ",
  " Digital Marketing and Data Analytics ",
  " Business Administration, Management and Operations ",
  " Digital Marketing and Data Analytics ",
  " Business Administration, Management and Operations ",
  " Digital Marketing and Data Analytics ",
  " Business Administration, Management and Operations ",
  " Communication and Media Studies ",
  " Cognitive Science ",
  " Cognitive Science ",
  " Bioengineering ",
  " Biomedical Engineering ",
  " Biochemistry ",
  " Synthetic Biology ",
  " Business Economics ",];
  var data = [
    {
      type: 'treemap',
      labels: labels,
      parents: parents,
      values: [10, 14, 12, 10, 2, 6, 6, 1, 4],
      textinfo: 'label+value+percent parent+percent entry',
      domain: { x: [0, 0.48] },
      outsidetextfont: { size: 20, color: '#377eb8' },
      marker: { line: { width: 2 } },
      pathbar: { visible: false },
    },
    {
      type: 'treemap',
      branchvalues: 'total',
      labels: labels,
      parents: parents,
      domain: { x: [0.52, 1] },
      values: [65, 14, 12, 10, 2, 6, 6, 1, 4],
      textinfo: 'label+value+percent parent+percent entry',
      outsidetextfont: { size: 20, color: '#377eb8' },
      marker: { line: { width: 2 } },
      pathbar: { visible: false },
    },
  ];
  var layout = {
    annotations: [
      {
        showarrow: false,
        text: 'branchvalues: <b>remainder</b>',
        x: 0.25,
        xanchor: 'center',
        y: 1.1,
        yanchor: 'bottom',
      },
      {
        showarrow: false,
        text: 'branchvalues: <b>total</b>',
        x: 0.75,
        xanchor: 'center',
        y: 1.1,
        yanchor: 'bottom',
      },
    ],
  };
  
  Plotly.newPlot('basic-tree', data);
  