const feb22_crimes_geojson = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4488659, 34.0615041],
      },
      properties: {
        'Event #': 2022005542,
        DATE: '2/1/22',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'WEYBURN COMMONS\n11020 WEYBURN DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0163',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4452356, 34.0737524],
      },
      properties: {
        'Event #': 2022005601,
        DATE: '2/2/22',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '300-BLOCK WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0165',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.445224, 34.0681721],
      },
      properties: {
        'Event #': 2022005603,
        DATE: '2/2/22',
        EVENT:
          'OBSTRUCT/RESIST/ETC PUBLIC/P OFFICER/EMT\n(2) MENTAL DISORDER 72 HR OBSERVATION',
        CATEGORY: 'OTHER/MULTIPLE\nOTHER/MULTIPLE',
        LOCATION: 'PARKING STRUCTURE 8\n555 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0164',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.454177, 34.06597],
      },
      properties: {
        'Event #': 2022005652,
        DATE: '2/2/22',
        EVENT: 'GRAND THEFT - MOTOR VEH PARTS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '624 VETERAN AVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0166',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4405426, 34.0483213],
      },
      properties: {
        'Event #': 2022005666,
        DATE: '2/2/22',
        EVENT:
          'RESTRICTED DRIVER OPERATE VEHICLE W/O INTERLOCK DEVICE\n(2) WARRANT ARREST',
        CATEGORY: 'TRAFFIC/VEHICULAR \nOTHER/MULTIPLE',
        LOCATION: '10984 SANTA MONICA BLVD',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0167',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4420175, 34.0660738],
      },
      properties: {
        'Event #': 2022005670,
        DATE: '2/2/22',
        EVENT: 'PETTY THEFT - BICYCLES',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'SCHOOL OF DENTISTRY\n714 TIVERTON AVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0168',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.45289, 34.0687236],
      },
      properties: {
        'Event #': 2022005683,
        DATE: '2/2/22',
        EVENT: 'THEFT BY USE OF ACCESS CARD INFORMATION',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '461 MIDVALE AVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0169',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.447971, 34.0619741],
      },
      properties: {
        'Event #': 2022005711,
        DATE: '2/2/22',
        EVENT:
          'OBSTRUCT/RESIST/ETC PUBLIC/P OFFICER/EMT\n(2) ILLEGAL POSSESSION OF SHOPPING CART',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '10999 WEYBURN AVE/GAYLEY AVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0171',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4368004, 34.0496764],
      },
      properties: {
        'Event #': 2022005744,
        DATE: '2/3/22',
        EVENT: 'DUI ALCOHOL\n(2) DUI ALCOHOL/0.08 PERCENT',
        CATEGORY: 'TRAFFIC/VEHICULAR\nTRAFFIC/VEHICULAR',
        LOCATION: '10858 SANTA MONICA BLVD/WESTWOOD BLVD',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0173',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4441451, 34.070418],
      },
      properties: {
        'Event #': 2022005823,
        DATE: '2/3/22',
        EVENT: 'PETTY THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'ACKERMAN UNION\n308 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0179',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4462008, 34.061131],
      },
      properties: {
        'Event #': 2022005848,
        DATE: '2/3/22',
        EVENT: 'BATTERY\n(2) VANDALISM ($400 OR MORE)',
        CATEGORY: 'ASSAULT/BATTERY\nVANDALISM',
        LOCATION: '1073 BROXTON AVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0180',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4489671, 34.068547],
      },
      properties: {
        'Event #': 2022005854,
        DATE: '2/3/22',
        EVENT: 'VANDALISM - DEFACE PROPERTY',
        CATEGORY: 'VANDALISM',
        LOCATION: '10900 STRATHMORE DRIVE/GAYLEY AVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0181',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4399532, 34.0771178],
      },
      properties: {
        'Event #': 2022005864,
        DATE: '2/3/22',
        EVENT: 'MALICIOUS MISCHIEF TO VEHICLE',
        CATEGORY: 'TRAFFIC/VEHICULAR',
        LOCATION: 'PARKING STRUCTURE 3\n215 CHARLES E YOUNG DRIVE N',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0182',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4488096, 34.06627657],
      },
      properties: {
        'Event #': 2022005975,
        DATE: '2/4/22',
        EVENT: 'VANDALISM - DEFACE PROPERTY',
        CATEGORY: 'VANDALISM',
        LOCATION: 'ALPHA EPSILON PI FRATERNITY\n645 LANDFAIR AVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0184',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4468107, 34.0593389],
      },
      properties: {
        'Event #': 2022006030,
        DATE: '2/4/22',
        EVENT: 'BURGLARY - FROM MOTOR VEHICLE',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '11000 KINROSS AVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0187',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4532399, 34.0700867],
      },
      properties: {
        'Event #': 2022006167,
        DATE: '2/5/22',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '403 LANDFAIR AVE\n403 LANDFAIR AVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0190',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.445224, 34.0681721],
      },
      properties: {
        'Event #': 2022006184,
        DATE: '2/5/22',
        EVENT: 'VANDALISM ($400 OR MORE)',
        CATEGORY: 'VANDALISM',
        LOCATION: 'PARKING STRUCTURE 8\n555 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0191',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.450844, 34.0621111],
      },
      properties: {
        'Event #': 2022006190,
        DATE: '2/5/22',
        EVENT: 'TRESPASS - REFUSE TO LEAVE PROPERTY',
        CATEGORY: 'TRESPASSING',
        LOCATION: 'OLIVE COURT\n825 WEYBURN TERRACE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0193',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.445224, 34.0681721],
      },
      properties: {
        'Event #': 2022006364,
        DATE: '2/6/22',
        EVENT: 'GRAND THEFT - AUTO',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'PARKING STRUCTURE 8\n555 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0198',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.449603, 34.0738529],
      },
      properties: {
        'Event #': 2022006446,
        DATE: '2/6/22',
        EVENT: 'GRAND THEFT - MOTOR VEH PARTS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'PARKING STRUCTURE RC\n113 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0200',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.442334, 34.0642451],
      },
      properties: {
        'Event #': 2022006464,
        DATE: '2/6/22',
        EVENT: 'ARSON - PROPERTY',
        CATEGORY: 'ARSON',
        LOCATION: 'GEFFEN HALL\n885 TIVERTON DRIVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0201',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4498776, 34.0462655],
      },
      properties: {
        'Event #': 2022006505,
        DATE: '2/6/22',
        EVENT: 'PARAPHERNALIA - POSSESS UNLAWFUL',
        CATEGORY: 'DRUG/CONTROLLED SUBSTANCE',
        LOCATION: '11335 SANTA MONICA BLVD',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0202',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4466512, 34.0652918],
      },
      properties: {
        'Event #': 2022006559,
        DATE: '2/7/22',
        EVENT: 'BATTERY',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: 'RRMC ER\n757 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0203',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.452112, 34.0721256],
      },
      properties: {
        'Event #': 2022006655,
        DATE: '2/7/22',
        EVENT: 'BATTERY',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: '280 DE NEVE DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0206',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4399532, 34.0771178],
      },
      properties: {
        'Event #': 2022006660,
        DATE: '2/7/22',
        EVENT: 'GRAND THEFT - FROM MOTOR VEHICLE',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'PARKING STRUCTURE 3\n215 CHARLES E YOUNG DRIVE N',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0205',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4449941, 34.0573696],
      },
      properties: {
        'Event #': 2022006690,
        DATE: '2/7/22',
        EVENT: 'POSSESS CONTROLLED SUBSTANCE\n(2) WARRANT ARREST',
        CATEGORY: 'DRUG/CONTROLLED SUBSTANCE\nOTHER/MULTIPLE',
        LOCATION: '1249 MIDVALE AVE/ASHTON AVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0208',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4515103, 34.0674302],
      },
      properties: {
        'Event #': 2022006710,
        DATE: '2/7/22',
        EVENT: 'PETTY THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '525 GLENROCK AVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0209',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.449603, 34.0738529],
      },
      properties: {
        'Event #': 2022006826,
        DATE: '2/8/22',
        EVENT: 'GRAND THEFT - MOTOR VEH PARTS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'PARKING STRUCTURE RC\n113 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0212',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4413024, 34.0736717],
      },
      properties: {
        'Event #': 2022006853,
        DATE: '2/8/22',
        EVENT: 'HATE INCIDENT',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'CAMPBELL HALL\n335 PORTOLA PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0213',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4466512, 34.0652918],
      },
      properties: {
        'Event #': 2022006867,
        DATE: '2/8/22',
        EVENT: 'BATTERY',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: 'RONALD REAGAN UCLA MEDICAL CENTER\n757 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0214',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4391737, 34.07432],
      },
      properties: {
        'Event #': 2022006883,
        DATE: '2/8/22',
        EVENT: 'PETTY THEFT - BICYCLES',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'PUBLIC AFFAIRS BUILDING\n337 CHARLES E YOUNG DRIVE E',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0216',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4449232, 34.0628113],
      },
      properties: {
        'Event #': 2022006907,
        DATE: '2/8/22',
        EVENT:
          'PETTY THEFT - BICYCLES\n(2) POSSESS CONTROLLED SUBSTANCE\n(3) WARRANT ARREST',
        CATEGORY: 'THEFT/BURGLARY\nDRUG/CONTROLLED SUBSTANCE\nOTHER/MULTIPLE',
        LOCATION: 'WESTWOOD PLAZA BUILDING\n924 WESTWOOD BLVD',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0217',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4484018, 34.059489],
      },
      properties: {
        'Event #': 2022006952,
        DATE: '2/8/22',
        EVENT: 'PARAPHERNALIA - POSSESS UNLAWFUL\n(2) WARRANT ARREST',
        CATEGORY: 'DRUG/CONTROLLED SUBSTANCE\nOTHER/MULTIPLE',
        LOCATION: '11099 KINROSS AVE/VETERAN AVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0220',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.442553, 34.0696278],
      },
      properties: {
        'Event #': 2022006954,
        DATE: '2/8/22',
        EVENT: 'VANDALISM - DAMAGE PROPERTY',
        CATEGORY: 'VANDALISM',
        LOCATION: 'MATHEMATICAL SCIENCES BUILDING\n520 PORTOLA PLAZA',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0221',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4466462, 34.0503956],
      },
      properties: {
        'Event #': 2022007009,
        DATE: '2/9/22',
        EVENT:
          'APPROPRIATE LOST PROPERTY\n(2) PARAPHERNALIA - POSSESS UNLAWFUL',
        CATEGORY: 'THEFT/BURGLARY\nDRUG/CONTROLLED SUBSTANCE',
        LOCATION: '1499 S SEPULVEDA BLVD/OHIO AVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0222',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4861171, 34.0272804],
      },
      properties: {
        'Event #': 2022007022,
        DATE: '2/9/22',
        EVENT: 'GRAND THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'UCLA SANTA MONICA HOSPITAL\n1250 16TH ST',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0224',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.3344941, 33.9376161],
      },
      properties: {
        'Event #': 2022007032,
        DATE: '2/9/22',
        EVENT: 'ANNOYING COMM - OBSCENE/THREATENING',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '3540 W 108TH ST',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0225',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4387112, 34.0726436],
      },
      properties: {
        'Event #': 2022007045,
        DATE: '2/9/22',
        EVENT: 'PETTY THEFT - OTHER',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'SCHOOL OF LAW\n385 CHARLES E YOUNG DRIVE E',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0231',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4441451, 34.070418],
      },
      properties: {
        'Event #': 2022007055,
        DATE: '2/9/22',
        EVENT: 'PETTY THEFT - SHOPLIFTING',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'ACKERMAN UNION\n308 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0228',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4861171, 34.0272804],
      },
      properties: {
        'Event #': 2022007056,
        DATE: '2/9/22',
        EVENT: 'PETTY THEFT - OTHER',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'UCLA SANTA MONICA HOSPITAL\n1250 16TH ST',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0227',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4399532, 34.0771178],
      },
      properties: {
        'Event #': 2022007089,
        DATE: '2/9/22',
        EVENT: 'TAMPER WITH VEHICLE',
        CATEGORY: 'VANDALISM',
        LOCATION: 'PARKING STRUCTURE 3\n215 CHARLES E YOUNG DRIVE N',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0232',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4588516, 34.0421776],
      },
      properties: {
        'Event #': 2022007118,
        DATE: '2/9/22',
        EVENT: 'PETTY THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'BOULEVARD APARTMENTS\n1515 S WESTGATE AVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0234',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.442553, 34.0696278],
      },
      properties: {
        'Event #': 2022007160,
        DATE: '2/10/22',
        EVENT: 'GIVE FALSE IDENTIFICATION TO PO\n(2) CA REGS - VIOLATE CURFEW',
        CATEGORY: 'OTHER/MULTIPLE\nOTHER/MULTIPLE',
        LOCATION: 'MATHEMATICAL SCIENCES BUILDING\n520 PORTOLA PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0235',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4286583, 34.0273761],
      },
      properties: {
        'Event #': 2022007192,
        DATE: '2/10/22',
        EVENT: 'PARAPHERNALIA - POSSESS UNLAWFUL\n(2) WARRANT ARREST',
        CATEGORY: 'DRUG/CONTROLLED SUBSTANCE\nOTHER/MULTIPLE',
        LOCATION: '2999 S SEPULVEDA BLVD/NATIONAL BLVD',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0236',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4479753, 34.0619716],
      },
      properties: {
        'Event #': 2022007197,
        DATE: '2/10/22',
        EVENT: 'POSSESS NARCOTIC CONTROLLED SUBSTANCE\n(2) DUI ALCOHOL',
        CATEGORY: 'DRUG/CONTROLLED SUBSTANCE\nTRAFFIC/VEHICULAR',
        LOCATION: '999 GAYLEY AVE/WEYBURN AVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0237',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4527487, 34.0739077],
      },
      properties: {
        'Event #': 2022007203,
        DATE: '2/10/22',
        EVENT: 'TRESPASSING\n(2) CA REGS - VIOLATE CURFEW',
        CATEGORY: 'TRESPASSING\nOTHER/MULTIPLE',
        LOCATION: 'HEDRICK SUMMIT\n240 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0238',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.448248, 34.065363],
      },
      properties: {
        'Event #': 2022007220,
        DATE: '2/10/22',
        EVENT: 'DISORDERLY CONDUCT - LOITER/ETC PRIVATE PROPERTY',
        CATEGORY: 'TRESPASSING',
        LOCATION: '705 GAYLEY AVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0239',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4451436, 34.0635092],
      },
      properties: {
        'Event #': 2022007266,
        DATE: '2/10/22',
        EVENT: 'GRAND THEFT - BICYCLES',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'CHICK-FIL-A\n900 WESTWOOD BLVD',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0242',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.445224, 34.0681721],
      },
      properties: {
        'Event #': 2022007384,
        DATE: '2/11/22',
        EVENT: 'DUI ALCOHOL',
        CATEGORY: 'TRAFFIC/VEHICULAR',
        LOCATION: 'PARKING STRUCTURE 8\n555 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0243',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4188382, 34.0118795],
      },
      properties: {
        'Event #': 2022007397,
        DATE: '2/11/22',
        EVENT: 'POSSESS NARCOTIC CONTROLLED SUBSTANCE\n(2) WARRANT ARREST',
        CATEGORY: 'DRUG/CONTROLLED SUBSTANCE\nOTHER/MULTIPLE',
        LOCATION: '11248 VENICE BLVD/GLOBE AVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0244',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4672792, 34.0007862],
      },
      properties: {
        'Event #': 2022007478,
        DATE: '2/11/22',
        EVENT: 'VANDALISM - DAMAGE PROPERTY',
        CATEGORY: 'VANDALISM',
        LOCATION: 'UCLA VENICE DENTAL CLINIC\n323 LINCOLN BLVD',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0246',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4466512, 34.0652918],
      },
      properties: {
        'Event #': 2022007507,
        DATE: '2/11/22',
        EVENT: 'BATTERY',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: 'RONALD REAGAN UCLA MEDICAL CENTER\n757 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0249',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4529816, 34.0729235],
      },
      properties: {
        'Event #': 2022007508,
        DATE: '2/11/22',
        EVENT: 'FALSE IMPRISONMENT',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'CENTENNIAL HALL\n265 DE NEVE DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0248',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4492046, 34.0646006],
      },
      properties: {
        'Event #': 2022007526,
        DATE: '2/11/22',
        EVENT: 'OBTAIN MONEY/ETC BY FALSE PRETENSES (OVER $950)',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '10982 ROEBLING AVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0250',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4456822, 34.0611317],
      },
      properties: {
        'Event #': 2022007571,
        DATE: '2/11/22',
        EVENT: 'DUI ALCOHOL\n(2) DUI ALCOHOL/0.08 PERCENT',
        CATEGORY: 'TRAFFIC/VEHICULAR\nTRAFFIC/VEHICULAR',
        LOCATION: '1099 WESTWOOD BLVD/KINROSS AVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0251',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4482758, 34.0683819],
      },
      properties: {
        'Event #': 2022007626,
        DATE: '2/12/22',
        EVENT:
          'THEFT BY USE OF ACCESS CARD INFORMATION\n(2) APPROPRIATE LOST PROPERTY\n(3) PARAPHERNALIA - POSSESS UNLAWFUL',
        CATEGORY: 'THEFT/BURGLARY\nTHEFT/BURGLARY\nDRUG/CONTROLLED SUBSTANCE',
        LOCATION: 'EH AND S SERVICES BUILDING\n550 CHARLES E YOUNG DRIVE W',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0252',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4372622, 34.07154099],
      },
      properties: {
        'Event #': 2022007780,
        DATE: '2/12/22',
        EVENT:
          'POSSESS CONTROLLED SUBSTANCE\n(2) PARAPHERNALIA - POSSESS UNLAWFUL\n(3) WARRANT ARREST\n(4) WARRANT ARREST',
        CATEGORY:
          'DRUG/CONTROLLED SUBSTANCE\nDRUG/CONTROLLED SUBSTANCE\nOTHER/MULTIPLE\nOTHER/MULTIPLE',
        LOCATION: '530 HILGARD AVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0253',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4445815, 34.0652658],
      },
      properties: {
        'Event #': 2022007806,
        DATE: '2/12/22',
        EVENT: 'ASSAULT',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: '300 STEIN PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0255',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4496163, 34.0645172],
      },
      properties: {
        'Event #': 2022007869,
        DATE: '2/13/22',
        EVENT: 'BURGLARY - HOT PROWL',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '10998 ROEBLING AVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0259',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4589644, 34.04205299],
      },
      properties: {
        'Event #': 2022007873,
        DATE: '2/13/22',
        EVENT: 'GRAND THEFT - AUTO',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'BOULEVARD APARTMENTS\n1515 S WESTGATE AVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0260',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4576637, 34.0425784],
      },
      properties: {
        'Event #': 2022007959,
        DATE: '2/13/22',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '1500 GRANVILLE AVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0261',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.441522, 34.066584],
      },
      properties: {
        'Event #': 2022008072,
        DATE: '2/14/22',
        EVENT: 'PETTY THEFT - OTHER',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'BOTANICAL GARDENS\n707 TIVERTON DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0263',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4495832, 34.0737767],
      },
      properties: {
        'Event #': 2022008142,
        DATE: '2/14/22',
        EVENT: 'OBTAIN MONEY/ETC BY FALSE PRETENSES',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '200 DE NEVE DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0270',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4521515, 34.0732145],
      },
      properties: {
        'Event #': 2022008161,
        DATE: '2/14/22',
        EVENT: 'PETTY THEFT - BICYCLES',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'HEDRICK HALL\n250 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0266',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4442897, 34.0670998],
      },
      properties: {
        'Event #': 2022008205,
        DATE: '2/14/22',
        EVENT:
          'VANDALISM - DAMAGE PROPERTY\n(2) PARAPHERNALIA - POSSESS UNLAWFUL',
        CATEGORY: 'VANDALISM\nDRUG/CONTROLLED SUBSTANCE',
        LOCATION: 'PARKING STRUCTURE 9\n675 CHARLES YOUND DRIVE S',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0268',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.461121, 34.067459],
      },
      properties: {
        'Event #': 2022008280,
        DATE: '2/15/22',
        EVENT:
          'BATTERY ON PEACE OFFICER/EMERGENCY PERSONNEL/ETC\n(2) POSSESS CONTROLLED SUBSTANCE\n(3) PARAPHERNALIA - POSSESS UNLAWFUL\n(4) OBSTRUCT/RESIST/ETC PUBLIC/P OFFICER/EMT',
        CATEGORY:
          'ASSAULT/BATTERY\nDRUG/CONTROLLED SUBSTANCE\nDRUG/CONTROLLED SUBSTANCE\nOTHER/MULTIPLE',
        LOCATION: '399 S SEPULVEDA BLVD/MONTANA AVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0269',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4486342, 34.0638872],
      },
      properties: {
        'Event #': 2022008428,
        DATE: '2/16/22',
        EVENT:
          'POSS >1OZ MJ BY PERSON OF ANY AGE\n(2) POSSESS NARCOTIC CONTROLLED SUBSTANCE',
        CATEGORY: 'DRUG/CONTROLLED SUBSTANCE\nDRUG/CONTROLLED SUBSTANCE',
        LOCATION: '10995 LE CONTE AVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0277',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4396381, 34.0715849],
      },
      properties: {
        'Event #': 2022008505,
        DATE: '2/16/22',
        EVENT: 'STALKING\n(2) TMU INVESTIGATION',
        CATEGORY: 'OTHER/MULTIPLE\nOTHER/MULTIPLE',
        LOCATION: '400-BLOCK CHARLES E YOUNG DRIVE E',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0280',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4469528, 34.059361],
      },
      properties: {
        'Event #': 2022008580,
        DATE: '2/16/22',
        EVENT:
          'GIVE FALSE IDENTIFICATION TO PO\n(2) POSSESS CONTROLLED SUBSTANCE\n(3) PARAPHERNALIA - POSSESS UNLAWFUL\n(4) TRESPASS - OCCUPY PROPERTY WITHOUT CONSENT',
        CATEGORY:
          'OTHER/MULTIPLE\nDRUG/CONTROLLED SUBSTANCE\nDRUG/CONTROLLED SUBSTANCE\nTRESPASSING',
        LOCATION: 'GEFFEN ACADEMY AT UCLA\n11000 KINROSS AVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0284',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4466512, 34.0652918],
      },
      properties: {
        'Event #': 2022008636,
        DATE: '2/17/22',
        EVENT: 'ASSAULT DEADLY WEAPON - NOT FIREARM\n(2) WARRANT ARREST',
        CATEGORY: 'ASSAULT/BATTERY\nOTHER/MULTIPLE',
        LOCATION: 'RONALD REAGAN UCLA MEDICAL CENTER\n757 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0286',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.443567, 34.073954],
      },
      properties: {
        'Event #': 2022008756,
        DATE: '2/17/22',
        EVENT:
          'THFT UTIL SRVS RCV BENEFT\n(2) GIVE FALSE IDENTIFICATION TO PO\n(3) WARRANT ARREST',
        CATEGORY: 'OTHER/MULTIPLE\nOTHER/MULTIPLE\nOTHER/MULTIPLE',
        LOCATION: 'ANDERSON SCHOOL OF MANAGEMENT\n110 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0291',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4237688, 34.0171491],
      },
      properties: {
        'Event #': 2022008822,
        DATE: '2/18/22',
        EVENT: 'DISTURB BY LOUD/UNREASONABLE NOISE',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'SAWTELLE APARTMENTS\n3110 SAWTELLE BLVD',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0292',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4519249, 34.0696865],
      },
      properties: {
        'Event #': 2022008885,
        DATE: '2/18/22',
        EVENT: 'BURGLARY - HOT PROWL\n(2) GRAND THEFT - AUTO',
        CATEGORY: 'THEFT/BURGLARY\nTHEFT/BURGLARY',
        LOCATION: '448 LANDFAIR AVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0294',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4454037, 34.0673085],
      },
      properties: {
        'Event #': 2022008886,
        DATE: '2/18/22',
        EVENT: 'MISCELLANEOUS PC CODE VIOLATION',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'UCLA POLICE STATION\n601 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '22-0293',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4441451, 34.070418],
      },
      properties: {
        'Event #': 2022008901,
        DATE: '2/18/22',
        EVENT: 'LOST PROPERTY',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'ACKERMAN UNION\n308 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '22-0295',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4533311, 34.0694242],
      },
      properties: {
        'Event #': 2022008912,
        DATE: '2/18/22',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '430 KELTON AVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0296',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4576637, 34.0425784],
      },
      properties: {
        'Event #': 2022008917,
        DATE: '2/18/22',
        EVENT: 'VANDALISM - DAMAGE PROPERTY',
        CATEGORY: 'VANDALISM',
        LOCATION: '1500 GRANVILLE AVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0297',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.448026, 34.0630706],
      },
      properties: {
        'Event #': 2022008963,
        DATE: '2/18/22',
        EVENT: 'GRAND THEFT - OTHER',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'IN N OUT BURGER\n922 GAYLEY AVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0299',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4494253, 34.0633376],
      },
      properties: {
        'Event #': 2022008991,
        DATE: '2/19/22',
        EVENT: 'BURGLARY - HOT PROWL\n(2) GRAND THEFT - AUTO',
        CATEGORY: 'THEFT/BURGLARY\nTHEFT/BURGLARY',
        LOCATION: 'MARGAN APARTMENTS\n885 LEVERING AVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0300',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.45289, 34.0687236],
      },
      properties: {
        'Event #': 2022008995,
        DATE: '2/19/22',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '461 MIDVALE AVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0301',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4441451, 34.070418],
      },
      properties: {
        'Event #': 2022009016,
        DATE: '2/19/22',
        EVENT: 'PETTY THEFT - OTHER',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'ACKERMAN UNION\n308 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0303',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4301382, 34.0251034],
      },
      properties: {
        'Event #': 2022009090,
        DATE: '2/19/22',
        EVENT: 'PETTY THEFT - BICYCLES',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '3110 SAWTELLE BLVD',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0305',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4415114, 34.0685828],
      },
      properties: {
        'Event #': 2022009132,
        DATE: '2/20/22',
        EVENT:
          'TRESPASS - OCCUPY PROPERTY WITHOUT CONSENT\n(2) CA REGS - VIOLATE CURFEW',
        CATEGORY: 'TRESPASSING\nOTHER/MULTIPLE',
        LOCATION: 'YOUNG HALL\n607 CHARLES E YOUNG DRIVE E',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0306',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4119828, 34.0272495],
      },
      properties: {
        'Event #': 2022009210,
        DATE: '2/20/22',
        EVENT: 'PETTY THEFT - FROM MOTOR VEHICLES',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'KEYSTONE APARTMENTS\n3780 KEYSTONE AVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0309',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4446824, 34.0673704],
      },
      properties: {
        'Event #': 2022009275,
        DATE: '2/20/22',
        EVENT: 'CA REGS - UNAUTHORIZED CAMPING ON UNIVERSITY PROPERTY',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'GONDA GOLDSCHMEID CENTER\n695 CHARLES E YOUNG DRIVE S',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0310',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.448893, 34.0566568],
      },
      properties: {
        'Event #': 2022009297,
        DATE: '2/20/22',
        EVENT:
          'OBSTRUCT/RESIST/ETC PUBLIC/P OFFICER/EMT\n(2) MISCELLANEOUS VEHICLE CODE',
        CATEGORY: 'OTHER/MULTIPLE\nOTHER/MULTIPLE',
        LOCATION: '1199 VETERAN AVE/WILSHIRE BLVD',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0311',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4497877, 34.0713431],
      },
      properties: {
        'Event #': 2022009316,
        DATE: '2/21/22',
        EVENT: 'EXTORTION',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'SPROUL LANDING\n380 DE NEVE DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0312',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4588516, 34.0421776],
      },
      properties: {
        'Event #': 2022009404,
        DATE: '2/21/22',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'BOULEVARD APARTMENTS\n1519 GRANVILLE AVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0314',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4441451, 34.070418],
      },
      properties: {
        'Event #': 2022009429,
        DATE: '2/21/22',
        EVENT: 'SHOPLIFTING',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'ACKERMAN UNION\n308 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0316',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.450844, 34.0621111],
      },
      properties: {
        'Event #': 2022009467,
        DATE: '2/21/22',
        EVENT: 'EXTORTION',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'OLIVE COURT\n825 WEYBURN TERRACE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0318',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4528758, 34.0714739],
      },
      properties: {
        'Event #': 2022009615,
        DATE: '2/22/22',
        EVENT: 'PROPERTY REPORT ONLY',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'PARKING LOT 13\n329 DE NEVE DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0320',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4861171, 34.0272804],
      },
      properties: {
        'Event #': 2022009652,
        DATE: '2/22/22',
        EVENT:
          'FELON/ADDICT/POSSESS/ETC FIREARM\n(2) CARRY LOADED FIREARM IN PUBLIC UNDER SPECIFIC CIRCUMSTANCES',
        CATEGORY: 'OTHER/MULTIPLE\nOTHER/MULTIPLE',
        LOCATION: 'UCLA SANTA MONICA HOSPITAL\n1250 16TH ST',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0322',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4466512, 34.0652918],
      },
      properties: {
        'Event #': 2022009713,
        DATE: '2/23/22',
        EVENT: 'BATTERY',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: 'RONALD REAGAN UCLA MEDICAL CENTER\n757 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0325',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4447794, 34.0667059],
      },
      properties: {
        'Event #': 2022009746,
        DATE: '2/23/22',
        EVENT:
          'TAMPER/ETC WITH FIRE ALARM/ETC\n(2) SEND/ETC FALSE FIRE ALARM BY ANY METHOD',
        CATEGORY: 'VANDALISM\nOTHER/MULTIPLE',
        LOCATION: '700-BLOCK WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0326',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4441451, 34.070418],
      },
      properties: {
        'Event #': 2022009780,
        DATE: '2/23/22',
        EVENT: 'PETTY THEFT - SHOPLIFTING\n(2) WARRANT ARREST',
        CATEGORY: 'THEFT/BURGLARY\nOTHER/MULTIPLE',
        LOCATION: 'ACKERMAN UNION\n308 WESTWOOD PLAZA',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0327',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4231885, 34.0211383],
      },
      properties: {
        'Event #': 2022009787,
        DATE: '2/23/22',
        EVENT: 'GRAND THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'ROSE APARTMENTS\n11130 ROSE AVE',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0328',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4537072, 34.0735276],
      },
      properties: {
        'Event #': 2022009818,
        DATE: '2/23/22',
        EVENT:
          'TRANSIENT FAIL 30 DAY UPDATE OF REGISTRATION\n(2) WARRANT ARREST',
        CATEGORY: 'OTHER/MULTIPLE\nOTHER/MULTIPLE',
        LOCATION: 'HITCH SUITES\n245 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0330',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4420221, 34.0661156],
      },
      properties: {
        'Event #': 2022009946,
        DATE: '2/24/22',
        EVENT: 'VANDALISM LESS THAN $400',
        CATEGORY: 'VANDALISM',
        LOCATION: 'CENTER FOR HEALTH SCIENCES\n10833 LE CONTE AVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0332',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.5227243, 34.2583522],
      },
      properties: {
        'Event #': 2022009974,
        DATE: '2/24/22',
        EVENT: 'OBTAIN MONEY/ETC BY FALSE PRETENSES (OVER $950)',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '10346 ZELZAH AVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0333',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4796117, 34.0161983],
      },
      properties: {
        'Event #': 2022010007,
        DATE: '2/24/22',
        EVENT: 'OBTAIN MONEY/ETC BY FALSE PRETENSES (OVER $950)',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '1837 12TH ST',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0334',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4387112, 34.0726436],
      },
      properties: {
        'Event #': 2022010186,
        DATE: '2/25/22',
        EVENT: 'AREA CHECK',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: 'SCHOOL OF LAW\n385 CHARLES E YOUNG DRIVE E',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '22-0337',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4441451, 34.070418],
      },
      properties: {
        'Event #': 2022010261,
        DATE: '2/25/22',
        EVENT: 'PETTY THEFT - OTHER',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'ACKERMAN UNION\n308 WESTWOOD PLAZA',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0341',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4446824, 34.0673704],
      },
      properties: {
        'Event #': 2022010299,
        DATE: '2/25/22',
        EVENT: 'GRAND THEFT - FROM BUILDINGS',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'GONDA GOLDSCHMEID CENTER\n695 CHARLES E YOUNG DRIVE S',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0343',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4499735, 34.0729973],
      },
      properties: {
        'Event #': 2022010397,
        DATE: '2/26/22',
        EVENT: 'VANDALISM - DAMAGE PROPERTY',
        CATEGORY: 'VANDALISM',
        LOCATION: 'COVEL COMMONS\n330 DE NEVE DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0344',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4382038, 34.0736792],
      },
      properties: {
        'Event #': 2022010485,
        DATE: '2/26/22',
        EVENT: 'GRAND THEFT - OTHER',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: '350 CHARLES E YOUNG DRIVE E/WYTON DRIVE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0346',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4399532, 34.0771178],
      },
      properties: {
        'Event #': 2022010493,
        DATE: '2/26/22',
        EVENT: 'TAMPER WITH VEHICLE',
        CATEGORY: 'VANDALISM',
        LOCATION: 'PARKING STRUCTURE 3\n215 CHARLES E YOUNG DRIVE N',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0347',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4451184, 34.0634784],
      },
      properties: {
        'Event #': 2022010798,
        DATE: '2/27/22',
        EVENT: 'ASSAULT DEADLY WEAPON - NOT FIREARM',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: '900 WESTWOOD BLVD',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0349',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4451184, 34.0634784],
      },
      properties: {
        'Event #': 2022010858,
        DATE: '2/28/22',
        EVENT:
          'ASSAULT ON PEACE OFFICER/FIREFIGHTERS/ETC\n(2) DISORDERLY CONDUCT - ALCOHOL',
        CATEGORY: 'ASSAULT/BATTERY\nOTHER/MULTIPLE',
        LOCATION: '900 WESTWOOD BLVD',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0350',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4499786, 34.0729953],
      },
      properties: {
        'Event #': 2022010920,
        DATE: '2/28/22',
        EVENT: 'TRANSIENT FAIL 30 DAY UPDATE OF REGISTRATION',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '330 DE NEVE DRIVE',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0351',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4473921, 34.0670903],
      },
      properties: {
        'Event #': 2022010928,
        DATE: '2/28/22',
        EVENT: 'TRAFFIC COLLIS UNIVERSITY VEH',
        CATEGORY: 'TRAFFIC/VEHICULAR',
        LOCATION:
          'CENTRAL GARAGE AND FLEET SERVICES\n761 CHARLES E YOUNG DRIVE S',
        DISPOSITION: 'OPEN CASE: TO BE ASSIGNED',
        'Case #': '22-0352',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4520113, 34.0633481],
      },
      properties: {
        'Event #': 2022010930,
        DATE: '2/28/22',
        EVENT: 'BURGLARY',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'CYPRESS COURT\n725 WEYBURN TERRACE',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0353',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.1315417, 34.0804349],
      },
      properties: {
        'Event #': 2022010951,
        DATE: '2/28/22',
        EVENT: 'OBTAIN MONEY/ETC BY FALSE PRETENSES (OVER $950)',
        CATEGORY: 'OTHER/MULTIPLE',
        LOCATION: '1110 S 8TH AVE.',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0358',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4399532, 34.0771178],
      },
      properties: {
        'Event #': 2022010968,
        DATE: '2/28/22',
        EVENT: 'TAMPER WITH VEHICLE',
        CATEGORY: 'VANDALISM',
        LOCATION: 'PARKING STRUCTURE 3\n215 CHARLES E YOUNG DRIVE N',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0360',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4407536, 34.0766862],
      },
      properties: {
        'Event #': 2022010970,
        DATE: '2/28/22',
        EVENT:
          'RAPE BY FORCE/FEAR/ETC\n(2) ORAL COP - VICTIM INTOX/ETC\n(3) SEX PENETRATION - FORCE/ETC',
        CATEGORY:
          'RAPE/OTHER SEX CRIME\nRAPE/OTHER SEX CRIME\nRAPE/OTHER SEX CRIME',
        LOCATION: '200-BLOCK CHARLES E YOUNG DRIVE N',
        DISPOSITION: 'OPEN CASE',
        'Case #': '22-0364',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4421592, 34.0728088],
      },
      properties: {
        'Event #': 2022010972,
        DATE: '2/28/22',
        EVENT: 'GRAND THEFT - BICYCLES',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'ROYCE HALL\n10745 DICKSON PLAZA',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0359',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.44158, 34.0706955],
      },
      properties: {
        'Event #': 2022010978,
        DATE: '2/28/22',
        EVENT: 'PETTY THEFT - BICYCLES',
        CATEGORY: 'THEFT/BURGLARY',
        LOCATION: 'PHYSICS AND ASTRONOMY BUILDING\n430 PORTOLA PLAZA',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0362',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4399532, 34.0771178],
      },
      properties: {
        'Event #': 2022010984,
        DATE: '2/28/22',
        EVENT: 'TAMPER WITH VEHICLE',
        CATEGORY: 'VANDALISM',
        LOCATION: 'PARKING STRUCTURE 3\n215 CHARLES E YOUNG DRIVE N',
        DISPOSITION: 'CLOSED: NO FURTHER ACTION',
        'Case #': '22-0363',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [-118.4861171, 34.0272804],
      },
      properties: {
        'Event #': 2022010999,
        DATE: '2/28/22',
        EVENT: 'ASSAULT',
        CATEGORY: 'ASSAULT/BATTERY',
        LOCATION: 'UCLA SANTA MONICA HOSPITAL\n1250 16TH ST',
        DISPOSITION: 'CLOSED: SUBJECT ARRESTED',
        'Case #': '22-0366',
      },
    },
  ],
};
